// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/model-service/model-service.proto

package model_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelService_ImportModel_FullMethodName                     = "/model_service.ModelService/ImportModel"
	ModelService_UpdateModel_FullMethodName                     = "/model_service.ModelService/UpdateModel"
	ModelService_DeleteModel_FullMethodName                     = "/model_service.ModelService/DeleteModel"
	ModelService_ChangeModelStatus_FullMethodName               = "/model_service.ModelService/ChangeModelStatus"
	ModelService_GetModel_FullMethodName                        = "/model_service.ModelService/GetModel"
	ModelService_GetModelByUuid_FullMethodName                  = "/model_service.ModelService/GetModelByUuid"
	ModelService_ListModelsByUuids_FullMethodName               = "/model_service.ModelService/ListModelsByUuids"
	ModelService_ListModels_FullMethodName                      = "/model_service.ModelService/ListModels"
	ModelService_ListModelsByIds_FullMethodName                 = "/model_service.ModelService/ListModelsByIds"
	ModelService_ListTypeModels_FullMethodName                  = "/model_service.ModelService/ListTypeModels"
	ModelService_SaveModelExperienceDialog_FullMethodName       = "/model_service.ModelService/SaveModelExperienceDialog"
	ModelService_GetModelExperienceDialog_FullMethodName        = "/model_service.ModelService/GetModelExperienceDialog"
	ModelService_GetModelExperienceDialogs_FullMethodName       = "/model_service.ModelService/GetModelExperienceDialogs"
	ModelService_DeleteModelExperienceDialog_FullMethodName     = "/model_service.ModelService/DeleteModelExperienceDialog"
	ModelService_SaveModelExperienceDialogRecord_FullMethodName = "/model_service.ModelService/SaveModelExperienceDialogRecord"
	ModelService_GetModelExperienceDialogRecords_FullMethodName = "/model_service.ModelService/GetModelExperienceDialogRecords"
)

// ModelServiceClient is the client API for ModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelServiceClient interface {
	// 模型导入
	ImportModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 导入模型更新
	UpdateModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 导入模型删除
	DeleteModel(ctx context.Context, in *DeleteModelReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 模型启用/关闭
	ChangeModelStatus(ctx context.Context, in *ModelStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ‌查询单个模型‌
	GetModel(ctx context.Context, in *GetModelReq, opts ...grpc.CallOption) (*ModelInfo, error)
	// 根据uuid获取modelId
	GetModelByUuid(ctx context.Context, in *GetModelByUuidReq, opts ...grpc.CallOption) (*ModelInfo, error)
	// 根据uuids查询modelId列表
	ListModelsByUuids(ctx context.Context, in *ListModelsByUuidsReq, opts ...grpc.CallOption) (*ModelInfos, error)
	// 导入模型列表展示
	ListModels(ctx context.Context, in *ListModelsReq, opts ...grpc.CallOption) (*ModelInfos, error)
	// 根据模型ID列表查询
	ListModelsByIds(ctx context.Context, in *ListModelsByIdsReq, opts ...grpc.CallOption) (*ModelInfos, error)
	// llm/rerank/embedding模型列表展示
	ListTypeModels(ctx context.Context, in *ListTypeModelsReq, opts ...grpc.CallOption) (*ModelInfos, error)
	// 保存模型体验对话（创建/更新）
	SaveModelExperienceDialog(ctx context.Context, in *SaveModelExperienceDialogReq, opts ...grpc.CallOption) (*ModelExperienceDialog, error)
	// 获取模型体验对话
	GetModelExperienceDialog(ctx context.Context, in *ModelExperienceDialogReq, opts ...grpc.CallOption) (*ModelExperienceDialog, error)
	// 获取模型体验对话列表
	GetModelExperienceDialogs(ctx context.Context, in *ListModelExperienceDialogReq, opts ...grpc.CallOption) (*ModelExperienceDialogs, error)
	// 删除模型体验对话
	DeleteModelExperienceDialog(ctx context.Context, in *ModelExperienceDialogReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 保存模型体验对话记录
	SaveModelExperienceDialogRecord(ctx context.Context, in *SaveModelExperienceDialogRecordReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取模型体验对话记录列表
	GetModelExperienceDialogRecords(ctx context.Context, in *GetModelExperienceDialogRecordsReq, opts ...grpc.CallOption) (*ModelExperienceDialogRecords, error)
}

type modelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServiceClient(cc grpc.ClientConnInterface) ModelServiceClient {
	return &modelServiceClient{cc}
}

func (c *modelServiceClient) ImportModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ModelService_ImportModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) UpdateModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ModelService_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteModel(ctx context.Context, in *DeleteModelReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ModelService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ChangeModelStatus(ctx context.Context, in *ModelStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ModelService_ChangeModelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) GetModel(ctx context.Context, in *GetModelReq, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, ModelService_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) GetModelByUuid(ctx context.Context, in *GetModelByUuidReq, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, ModelService_GetModelByUuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListModelsByUuids(ctx context.Context, in *ListModelsByUuidsReq, opts ...grpc.CallOption) (*ModelInfos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfos)
	err := c.cc.Invoke(ctx, ModelService_ListModelsByUuids_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListModels(ctx context.Context, in *ListModelsReq, opts ...grpc.CallOption) (*ModelInfos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfos)
	err := c.cc.Invoke(ctx, ModelService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListModelsByIds(ctx context.Context, in *ListModelsByIdsReq, opts ...grpc.CallOption) (*ModelInfos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfos)
	err := c.cc.Invoke(ctx, ModelService_ListModelsByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListTypeModels(ctx context.Context, in *ListTypeModelsReq, opts ...grpc.CallOption) (*ModelInfos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfos)
	err := c.cc.Invoke(ctx, ModelService_ListTypeModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) SaveModelExperienceDialog(ctx context.Context, in *SaveModelExperienceDialogReq, opts ...grpc.CallOption) (*ModelExperienceDialog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelExperienceDialog)
	err := c.cc.Invoke(ctx, ModelService_SaveModelExperienceDialog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) GetModelExperienceDialog(ctx context.Context, in *ModelExperienceDialogReq, opts ...grpc.CallOption) (*ModelExperienceDialog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelExperienceDialog)
	err := c.cc.Invoke(ctx, ModelService_GetModelExperienceDialog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) GetModelExperienceDialogs(ctx context.Context, in *ListModelExperienceDialogReq, opts ...grpc.CallOption) (*ModelExperienceDialogs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelExperienceDialogs)
	err := c.cc.Invoke(ctx, ModelService_GetModelExperienceDialogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteModelExperienceDialog(ctx context.Context, in *ModelExperienceDialogReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ModelService_DeleteModelExperienceDialog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) SaveModelExperienceDialogRecord(ctx context.Context, in *SaveModelExperienceDialogRecordReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ModelService_SaveModelExperienceDialogRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) GetModelExperienceDialogRecords(ctx context.Context, in *GetModelExperienceDialogRecordsReq, opts ...grpc.CallOption) (*ModelExperienceDialogRecords, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelExperienceDialogRecords)
	err := c.cc.Invoke(ctx, ModelService_GetModelExperienceDialogRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServiceServer is the server API for ModelService service.
// All implementations must embed UnimplementedModelServiceServer
// for forward compatibility.
type ModelServiceServer interface {
	// 模型导入
	ImportModel(context.Context, *ModelInfo) (*emptypb.Empty, error)
	// 导入模型更新
	UpdateModel(context.Context, *ModelInfo) (*emptypb.Empty, error)
	// 导入模型删除
	DeleteModel(context.Context, *DeleteModelReq) (*emptypb.Empty, error)
	// 模型启用/关闭
	ChangeModelStatus(context.Context, *ModelStatusReq) (*emptypb.Empty, error)
	// ‌查询单个模型‌
	GetModel(context.Context, *GetModelReq) (*ModelInfo, error)
	// 根据uuid获取modelId
	GetModelByUuid(context.Context, *GetModelByUuidReq) (*ModelInfo, error)
	// 根据uuids查询modelId列表
	ListModelsByUuids(context.Context, *ListModelsByUuidsReq) (*ModelInfos, error)
	// 导入模型列表展示
	ListModels(context.Context, *ListModelsReq) (*ModelInfos, error)
	// 根据模型ID列表查询
	ListModelsByIds(context.Context, *ListModelsByIdsReq) (*ModelInfos, error)
	// llm/rerank/embedding模型列表展示
	ListTypeModels(context.Context, *ListTypeModelsReq) (*ModelInfos, error)
	// 保存模型体验对话（创建/更新）
	SaveModelExperienceDialog(context.Context, *SaveModelExperienceDialogReq) (*ModelExperienceDialog, error)
	// 获取模型体验对话
	GetModelExperienceDialog(context.Context, *ModelExperienceDialogReq) (*ModelExperienceDialog, error)
	// 获取模型体验对话列表
	GetModelExperienceDialogs(context.Context, *ListModelExperienceDialogReq) (*ModelExperienceDialogs, error)
	// 删除模型体验对话
	DeleteModelExperienceDialog(context.Context, *ModelExperienceDialogReq) (*emptypb.Empty, error)
	// 保存模型体验对话记录
	SaveModelExperienceDialogRecord(context.Context, *SaveModelExperienceDialogRecordReq) (*emptypb.Empty, error)
	// 获取模型体验对话记录列表
	GetModelExperienceDialogRecords(context.Context, *GetModelExperienceDialogRecordsReq) (*ModelExperienceDialogRecords, error)
	mustEmbedUnimplementedModelServiceServer()
}

// UnimplementedModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelServiceServer struct{}

func (UnimplementedModelServiceServer) ImportModel(context.Context, *ModelInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportModel not implemented")
}
func (UnimplementedModelServiceServer) UpdateModel(context.Context, *ModelInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedModelServiceServer) DeleteModel(context.Context, *DeleteModelReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedModelServiceServer) ChangeModelStatus(context.Context, *ModelStatusReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeModelStatus not implemented")
}
func (UnimplementedModelServiceServer) GetModel(context.Context, *GetModelReq) (*ModelInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedModelServiceServer) GetModelByUuid(context.Context, *GetModelByUuidReq) (*ModelInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelByUuid not implemented")
}
func (UnimplementedModelServiceServer) ListModelsByUuids(context.Context, *ListModelsByUuidsReq) (*ModelInfos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModelsByUuids not implemented")
}
func (UnimplementedModelServiceServer) ListModels(context.Context, *ListModelsReq) (*ModelInfos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelServiceServer) ListModelsByIds(context.Context, *ListModelsByIdsReq) (*ModelInfos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModelsByIds not implemented")
}
func (UnimplementedModelServiceServer) ListTypeModels(context.Context, *ListTypeModelsReq) (*ModelInfos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTypeModels not implemented")
}
func (UnimplementedModelServiceServer) SaveModelExperienceDialog(context.Context, *SaveModelExperienceDialogReq) (*ModelExperienceDialog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveModelExperienceDialog not implemented")
}
func (UnimplementedModelServiceServer) GetModelExperienceDialog(context.Context, *ModelExperienceDialogReq) (*ModelExperienceDialog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelExperienceDialog not implemented")
}
func (UnimplementedModelServiceServer) GetModelExperienceDialogs(context.Context, *ListModelExperienceDialogReq) (*ModelExperienceDialogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelExperienceDialogs not implemented")
}
func (UnimplementedModelServiceServer) DeleteModelExperienceDialog(context.Context, *ModelExperienceDialogReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModelExperienceDialog not implemented")
}
func (UnimplementedModelServiceServer) SaveModelExperienceDialogRecord(context.Context, *SaveModelExperienceDialogRecordReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveModelExperienceDialogRecord not implemented")
}
func (UnimplementedModelServiceServer) GetModelExperienceDialogRecords(context.Context, *GetModelExperienceDialogRecordsReq) (*ModelExperienceDialogRecords, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelExperienceDialogRecords not implemented")
}
func (UnimplementedModelServiceServer) mustEmbedUnimplementedModelServiceServer() {}
func (UnimplementedModelServiceServer) testEmbeddedByValue()                      {}

// UnsafeModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServiceServer will
// result in compilation errors.
type UnsafeModelServiceServer interface {
	mustEmbedUnimplementedModelServiceServer()
}

func RegisterModelServiceServer(s grpc.ServiceRegistrar, srv ModelServiceServer) {
	// If the following call pancis, it indicates UnimplementedModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelService_ServiceDesc, srv)
}

func _ModelService_ImportModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ImportModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ImportModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ImportModel(ctx, req.(*ModelInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).UpdateModel(ctx, req.(*ModelInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteModel(ctx, req.(*DeleteModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ChangeModelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ChangeModelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ChangeModelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ChangeModelStatus(ctx, req.(*ModelStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).GetModel(ctx, req.(*GetModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_GetModelByUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelByUuidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).GetModelByUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_GetModelByUuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).GetModelByUuid(ctx, req.(*GetModelByUuidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListModelsByUuids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsByUuidsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListModelsByUuids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListModelsByUuids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListModelsByUuids(ctx, req.(*ListModelsByUuidsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListModels(ctx, req.(*ListModelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListModelsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListModelsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListModelsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListModelsByIds(ctx, req.(*ListModelsByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListTypeModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTypeModelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListTypeModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListTypeModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListTypeModels(ctx, req.(*ListTypeModelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_SaveModelExperienceDialog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveModelExperienceDialogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).SaveModelExperienceDialog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_SaveModelExperienceDialog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).SaveModelExperienceDialog(ctx, req.(*SaveModelExperienceDialogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_GetModelExperienceDialog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelExperienceDialogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).GetModelExperienceDialog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_GetModelExperienceDialog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).GetModelExperienceDialog(ctx, req.(*ModelExperienceDialogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_GetModelExperienceDialogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelExperienceDialogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).GetModelExperienceDialogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_GetModelExperienceDialogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).GetModelExperienceDialogs(ctx, req.(*ListModelExperienceDialogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteModelExperienceDialog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelExperienceDialogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteModelExperienceDialog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteModelExperienceDialog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteModelExperienceDialog(ctx, req.(*ModelExperienceDialogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_SaveModelExperienceDialogRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveModelExperienceDialogRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).SaveModelExperienceDialogRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_SaveModelExperienceDialogRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).SaveModelExperienceDialogRecord(ctx, req.(*SaveModelExperienceDialogRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_GetModelExperienceDialogRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelExperienceDialogRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).GetModelExperienceDialogRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_GetModelExperienceDialogRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).GetModelExperienceDialogRecords(ctx, req.(*GetModelExperienceDialogRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelService_ServiceDesc is the grpc.ServiceDesc for ModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model_service.ModelService",
	HandlerType: (*ModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportModel",
			Handler:    _ModelService_ImportModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _ModelService_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _ModelService_DeleteModel_Handler,
		},
		{
			MethodName: "ChangeModelStatus",
			Handler:    _ModelService_ChangeModelStatus_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _ModelService_GetModel_Handler,
		},
		{
			MethodName: "GetModelByUuid",
			Handler:    _ModelService_GetModelByUuid_Handler,
		},
		{
			MethodName: "ListModelsByUuids",
			Handler:    _ModelService_ListModelsByUuids_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ModelService_ListModels_Handler,
		},
		{
			MethodName: "ListModelsByIds",
			Handler:    _ModelService_ListModelsByIds_Handler,
		},
		{
			MethodName: "ListTypeModels",
			Handler:    _ModelService_ListTypeModels_Handler,
		},
		{
			MethodName: "SaveModelExperienceDialog",
			Handler:    _ModelService_SaveModelExperienceDialog_Handler,
		},
		{
			MethodName: "GetModelExperienceDialog",
			Handler:    _ModelService_GetModelExperienceDialog_Handler,
		},
		{
			MethodName: "GetModelExperienceDialogs",
			Handler:    _ModelService_GetModelExperienceDialogs_Handler,
		},
		{
			MethodName: "DeleteModelExperienceDialog",
			Handler:    _ModelService_DeleteModelExperienceDialog_Handler,
		},
		{
			MethodName: "SaveModelExperienceDialogRecord",
			Handler:    _ModelService_SaveModelExperienceDialogRecord_Handler,
		},
		{
			MethodName: "GetModelExperienceDialogRecords",
			Handler:    _ModelService_GetModelExperienceDialogRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/model-service/model-service.proto",
}
