services:
  nginx:
    restart: always
    image: ${WANWU_NGINX_IMAGE}
    container_name: ${WANWU_NGINX_HOST}
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - ${WANWU_EXTERNAL_PORT}:8081
    volumes:
      - ./configs/middleware/nginx/conf.d:/etc/nginx/conf.d
      - ${WANWU_PROJECT_DIR}/nginx/html:/usr/share/nginx/html
      - ${WANWU_PROJECT_DIR}/nginx/log:/var/log/nginx

  # ------ microservice ------
  bff-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: bff-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 6668:6668
    volumes:
      - /etc/localtime:/etc/localtime
      - wanwu_shared_data_wga_sandbox_rag:/shared/data/wga/sandbox/rag
      - ./bin/${WANWU_ARCH}/bff-service:/app/bin/bff-service
      - ./configs/microservice/bff-service/configs:/app/configs/microservice/bff-service/configs
      - ./configs/microservice/bff-service/static:/app/configs/microservice/bff-service/static
      - ${WANWU_PROJECT_DIR}/bff-service/cache:/app/cache
      - ${WANWU_PROJECT_DIR}/bff-service/log:/app/log
      - ${WANWU_PROJECT_DIR}/bff-service/tmp:/app/tmp
      - ${WANWU_BFF_OAUTH_RSA_PRIVATE_KEY_PATH}:/app/tmp/oauth_rsa_private.pem
      - ${WANWU_BFF_OAUTH_RSA_PUBLIC_KEY_PATH}:/app/tmp/oauth_rsa_public.pem
    environment:
      CUSTOM_INFO_VERSION: ${WANWU_VERSION}
      SERVER_WEB_BASE_URL: ${WANWU_WEB_BASE_URL}
      SERVER_API_BASE_URL: ${WANWU_API_BASE_URL}
      SERVER_APP_OPEN_BASE_URL: ${WANWU_APP_OPEN_BASE_URL}
      WORKFLOW_TEMPLATE_SERVER_MODE: ${WANWU_BFF_WORKFLOW_TEMPLATE_SERVER_MODE}
      WORKFLOW_TEMPLATE_GLOBAL_WEB_LIST_URL: ${WANWU_BFF_WORKFLOW_TEMPLATE_GLOBAL_WEB_LIST_URL}
      WORKFLOW_TEMPLATE_LIST_URL: ${WANWU_BFF_WORKFLOW_TEMPLATE_LIST_URL}
      WORKFLOW_TEMPLATE_RECOMMEND_URL: ${WANWU_BFF_WORKFLOW_TEMPLATE_RECOMMEND_URL}
      WORKFLOW_TEMPLATE_DETAIL_URL: ${WANWU_BFF_WORKFLOW_TEMPLATE_DETAIL_URL}
      WORKFLOW_TEMPLATE_DOWNLOAD_URL: ${WANWU_BFF_WORKFLOW_TEMPLATE_DOWNLOAD_URL}
      MINIO_ENDPOINT: ${WANWU_MINIO_ENDPOINT}
      MINIO_USER: ${WANWU_MINIO_USER}
      MINIO_PASSWORD: ${WANWU_MINIO_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
      JWT_SIGNING_KEY: ${WANWU_BFF_JWT_SIGNING_KEY}
      CUSTOM_INFO_REGISTER_BY_EMAIL: ${WANWU_BFF_REGISTER_BY_EMAIL}
      CUSTOM_INFO_RESET_PASSWORD_BY_EMAIL: ${WANWU_BFF_RESET_PASSWORD_BY_EMAIL}
      CUSTOM_INFO_LOGIN_BY_EMAIL: ${WANWU_BFF_LOGIN_BY_EMAIL}
      OAUTH_SWITCH: ${WANWU_BFF_OAUTH_SWITCH}
    working_dir: /app
    command: ./bin/bff-service

  iam-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: iam-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8888:8888
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/iam-service:/app/bin/iam-service
      - ./configs/microservice/iam-service/configs:/app/configs/microservice/iam-service/configs
      - ${WANWU_PROJECT_DIR}/iam-service/log:/app/log
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
      SMTP_HOST: ${WANWU_IAM_SMTP_HOST}
      SMTP_PORT: ${WANWU_IAM_SMTP_PORT}
      SMTP_USERNAME: ${WANWU_IAM_SMTP_USERNAME}
      SMTP_PASSWORD: ${WANWU_IAM_SMTP_PASSWORD}
      SMTP_DEFAULT_FROM_EMAIL: ${WANWU_IAM_SMTP_DEFAULT_FROM_EMAIL}
      SMTP_DEFAULT_FROM_NAME: ${WANWU_IAM_SMTP_DEFAULT_FROM_NAME}
    working_dir: /app
    command: ./bin/iam-service

  model-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: model-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/model-service:/app/bin/model-service
      - ./configs/microservice/model-service/configs:/app/configs/microservice/model-service/configs
      - ${WANWU_PROJECT_DIR}/model-service/log:/app/log
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
    working_dir: /app
    command: ./bin/model-service

  mcp-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: mcp-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 9898:9898
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/mcp-service:/app/bin/mcp-service
      - ./configs/microservice/mcp-service/configs:/app/configs/microservice/mcp-service/configs
      - ${WANWU_PROJECT_DIR}/mcp-service/log:/app/log
    environment:
      SERVER_API_BASE_URL: ${WANWU_API_BASE_URL}
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
    working_dir: /app
    command: ./bin/mcp-service

  knowledge-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: knowledge-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8889:8889
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/knowledge-service:/app/bin/knowledge-service
      - ./configs/microservice/knowledge-service/configs:/app/configs/microservice/knowledge-service/configs
      - ${WANWU_PROJECT_DIR}/knowledge-service/log:/app/log
      - ${WANWU_PROJECT_DIR}/knowledge-service/static:/app/static
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      KAFKA_ADDR: ${WANWU_KAFKA_ADDRESS}
      KAFKA_USER: ${WANWU_KAFKA_USER}
      KAFKA_PASSWORD: ${WANWU_KAFKA_PASSWORD}
      MINIO_ENDPOINT: ${WANWU_MINIO_ENDPOINT}
      MINIO_USER: ${WANWU_MINIO_USER}
      MINIO_PASSWORD: ${WANWU_MINIO_PASSWORD}
    working_dir: /app
    command: ./bin/knowledge-service

  rag-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: rag-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 9640:9640
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/rag-service:/app/bin/rag-service
      - ./configs/microservice/rag-service/configs:/app/configs/microservice/rag-service/configs
      - ${WANWU_PROJECT_DIR}/rag-service/log:/app/log
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
    working_dir: /app
    command: ./bin/rag-service

  assistant-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: assistant-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8890:8890
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/assistant-service:/app/bin/assistant-service
      - ./configs/microservice/assistant-service/configs:/app/configs/microservice/assistant-service/configs
      - ${WANWU_PROJECT_DIR}/assistant-service/log:/app/log
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
      MINIO_ENDPOINT: ${WANWU_MINIO_ENDPOINT}
      MINIO_USER: ${WANWU_MINIO_USER}
      MINIO_PASSWORD: ${WANWU_MINIO_PASSWORD}
      MINIO_DOWNLOAD_URL: ${WANWU_WEB_BASE_URL}/minio/download/api/
      ES_ADDRESS: ${WANWU_ELASTIC_ADDRESS}
      ES_USERNAME: ${WANWU_ELASTIC_USER}
      ES_PASSWORD: ${WANWU_ELASTIC_PASSWORD}
    working_dir: /app
    command: ./bin/assistant-service

  agent-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: agent-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8990:8990
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/agent-service:/app/bin/agent-service
      - ./configs/microservice/agent-service/configs:/app/configs/microservice/agent-service/configs
      - ./configs/microservice/agent-service/tool-template:/app/configs/microservice/agent-service/tool-template
      - ${WANWU_PROJECT_DIR}/agent-service/log:/app/log
    environment:
      MINIO_ENDPOINT: ${WANWU_MINIO_ENDPOINT}
      MINIO_USER: ${WANWU_MINIO_USER}
      MINIO_PASSWORD: ${WANWU_MINIO_PASSWORD}
    working_dir: /app
    command: ./bin/agent-service

  operate-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: operate-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 9797:9797
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/operate-service:/app/bin/operate-service
      - ${WANWU_PROJECT_DIR}/operate-service/log:/app/log
      - ./configs/microservice/operate-service/configs:/app/configs/microservice/operate-service/configs
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
    working_dir: /app
    command: ./bin/operate-service

  app-service:
    restart: always
    image: ${WANWU_GO_IMAGE}
    container_name: app-service
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 9988:9988
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bin/${WANWU_ARCH}/app-service:/app/bin/app-service
      - ./configs/microservice/app-service/configs:/app/configs/microservice/app-service/configs
      - ${WANWU_PROJECT_DIR}/app-service/log:/app/log
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
      MINIO_ENDPOINT: ${WANWU_MINIO_ENDPOINT}
      MINIO_USER: ${WANWU_MINIO_USER}
      MINIO_PASSWORD: ${WANWU_MINIO_PASSWORD}
    working_dir: /app
    command: ./bin/app-service

  callback:
    restart: always
    image: ${WANWU_CALLBACK_BASE_IMAGE}
    container_name: callback-wanwu
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8669:8669
    volumes:
      - ./callback:/callback
      - ${WANWU_PROJECT_DIR}/callback-wanwu/log:/callback/log
    environment:
      MINIO_ENDPOINT: ${WANWU_MINIO_ENDPOINT}
      MINIO_USER: ${WANWU_MINIO_USER}
      MINIO_PASSWORD: ${WANWU_MINIO_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
      URL_RAG_DOC_PARSER: http://rag-wanwu:8681/rag/doc_parser
      URL_MINIO_DOWNLOAD: ${WANWU_WEB_BASE_URL}/minio/download/api
      WANWU_CALLBACK_URL_TO_BASE64: http://bff-service:6668/callback/v1/file/url/base64  
      GUNICORN_WORKERS: 2
      GUNICORN_TIMEOUT: 600
      GUNICORN_THREADS: 4

  workflow:
    restart: always
    image: ${WANWU_WORKFLOW_BASE_IMAGE}
    container_name: workflow-wanwu
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8998:8998
      - 8999:8999
    volumes:
      - /etc/localtime:/etc/localtime
      - ../wanwu-workflow/wanwu-backend/bin/${WANWU_ARCH}/workflow-wanwu:/app/bin/workflow-wanwu
      - ../wanwu-workflow/wanwu-backend/configs:/app/configs
      - ../wanwu-workflow/backend/infra/impl/document/parser/builtin/parse_pdf.py:/app/parse_pdf.py
      - ../wanwu-workflow/backend/infra/impl/document/parser/builtin/parse_docx.py:/app/parse_docx.py
      - ../wanwu-workflow/backend/infra/impl/coderunner/script/sandbox.py:/app/sandbox.py
      - ${WANWU_PROJECT_DIR}/workflow-wanwu/log:/app/log
    environment:
      DB_NAME: ${WANWU_DB_NAME}
      DB_MYSQL_ADDRESS: ${WANWU_MYSQL_ADDRESS}
      DB_MYSQL_PASSWORD: ${WANWU_MYSQL_PASSWORD}
      DB_TIDB_ADDRESS: ${WANWU_TIDB_ADDRESS}
      DB_TIDB_PASSWORD: ${WANWU_TIDB_PASSWORD}
      DB_OCEANBASE_USER: ${WANWU_OCEAN_BASE_USER}@${WANWU_OCEAN_BASE_TENANT_NAME}
      DB_OCEANBASE_ADDRESS: ${WANWU_OCEAN_BASE_HOST}:${WANWU_OCEAN_BASE_PORT}
      DB_OCEANBASE_PASSWORD: ${WANWU_OCEAN_BASE_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWORD: ${WANWU_REDIS_PASSWORD}
      MINIO_ENDPOINT: ${WANWU_MINIO_ENDPOINT}
      MINIO_USER: ${WANWU_MINIO_USER}
      MINIO_PASSWORD: ${WANWU_MINIO_PASSWORD}
      JWT_SIGNING_KEY: ${WANWU_BFF_JWT_SIGNING_KEY}
      # --- 以下env用于workflow-wanwu适配 ---
      WANWU_EXTERNAL_ENDPOINT: ${WANWU_EXTERNAL_ENDPOINT}
      WANWU_EXTERNAL_SCHEME: ${WANWU_EXTERNAL_SCHEME}
      WANWU_CALLBACK_LLM_BASE_URL: http://bff-service:6668/callback/v1/model
      WANWU_CALLBACK_SQUARE_TOOL_URL: http://bff-service:6668/callback/v1/workflow/tool/square
      WANWU_CALLBACK_CUSTOM_TOOL_URL: http://bff-service:6668/callback/v1/workflow/tool/custom
      WANWU_CALLBACK_WORKFLOW_LIST_URL: http://bff-service:6668/callback/v1/workflow/list
      WANWU_CALLBACK_CHATFLOW_LIST_URL: http://bff-service:6668/callback/v1/chatflow/list
      WANWU_CALLBACK_MCP_GET_URL: http://bff-service:6668/callback/v1/mcp
      WANWU_CALLBACK_MCP_SERVER_GET_URL: http://bff-service:6668/callback/v1/mcp/server
      WANWU_CALLBACK_WORKFLOW_LIST_SCHEMA_URL: http://workflow-wanwu:8999/v1/workflow/list_schema_by_wanwu
      WANWU_AGENT_API_URL: http://agent-service:8990/agent/chat/direct
      WANWU_KNOWLEDGE_SEARCH_URL: http://bff-service:6668/callback/v1/rag/search-knowledge-base
      WANWU_FILE_GENERATOR_URL: http://callback-wanwu:8669/v1/generate_file
      WANWU_FILE_PARSER_URL: http://rag-wanwu:8681/rag/doc_parser
      WANWU_QA_SEARCH_URL: http://bff-service:6668/callback/v1/rag/search-QA-base
      WANWU_CALLBACK_APP_RECORD_URL: http://bff-service:6668/callback/v1/app/record
      # 用于openapi调用workflow是否跳过execute history；默认0不跳过，会记录execute history；追求高并发为1不记录
      WANWU_WORKFLOW_OPENAPI_RUN_SKIP_EXECUTE_HISTORY: ${WANWU_WORKFLOW_OPENAPI_RUN_SKIP_EXECUTE_HISTORY}
      # 用于nginx 8081代理workflow-wanwu:8998 minio presign相关api
      WANWU_MINIO_PROXY_ENDPOINT: ${WANWU_EXTERNAL_ENDPOINT}
      WANWU_MINIO_PROXY_PREFIX: /workflow/minio/presign
      # 用于workflow-wanwu:8998代理minio-wanwu:9000
      MINIO_API_HOST: http://${WANWU_MINIO_ENDPOINT}
      MINIO_PROXY_ENDPOINT: :8998
      # 用于code节点运行
      CODE_RUNNER_TYPE: ${WANWU_WORKFLOW_CODE_RUNNER_TYPE}
      CODE_RUNNER_ALLOW_ENV:
      CODE_RUNNER_ALLOW_READ:
      CODE_RUNNER_ALLOW_WRITE:
      CODE_RUNNER_ALLOW_RUN: "python"
      CODE_RUNNER_ALLOW_NET: ${WANWU_EXTERNAL_IP},jsr.io,cdn.jsdelivr.net
      CODE_RUNNER_ALLOW_FFI:
      CODE_RUNNER_NODE_MODULES_DIR:
      CODE_RUNNER_TIMEOUT_SECONDS:
      CODE_RUNNER_MEMORY_LIMIT_MB:
    working_dir: /app
    command: ./bin/workflow-wanwu

  rag:
    restart: always
    image: ${WANWU_RAG_BASE_IMAGE}
    container_name: rag-wanwu
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 8613:8613
      - 8681:8681
      - 10891:10891
      - 15000:15000
    volumes:
      - wanwu_shared_data_wga_sandbox_rag:/shared/data/wga/sandbox/rag
      - ./rag/rag_open_source:/model_extend
      - ${WANWU_PROJECT_DIR}/rag-wanwu/rag_core/logs:/model_extend/rag_core/logs
      - ${WANWU_PROJECT_DIR}/rag-wanwu/rag_es_server_unify/logs:/model_extend/rag_es_server_unify/logs
    environment:
      MINIO_ADDRESS: ${WANWU_MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${WANWU_MINIO_USER}
      MINIO_SECRET_KEY: ${WANWU_MINIO_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${WANWU_KAFKA_ADDRESS}
      KAFKA_SASL_PLAIN_USERNAME: ${WANWU_KAFKA_USER}
      KAFKA_SASL_PLAIN_PASSWORD: ${WANWU_KAFKA_PASSWORD}
      ES_HOSTS: https://${WANWU_ELASTIC_ADDRESS}
      ES_USER: ${WANWU_ELASTIC_USER}
      ES_PASSWORD: ${WANWU_ELASTIC_PASSWORD}
      REDIS_HOST: ${WANWU_REDIS_HOST}
      REDIS_PORT: ${WANWU_REDIS_PORT}
      REDIS_PASSWD: ${WANWU_REDIS_PASSWORD}
      # 用于rag调用外部API的env
      GET_KB_ID_URL: http://bff-service:6668/v1/api/category/info
      KAFKA_MQ_REL_URL: http://bff-service:6668/v1/api/docstatus
      KAFKA_MQ_KB_STATUS_URL: http://bff-service:6668/v1/api/knowledge/status
      KAFKA_DOC_STATUS_INIT_URL: http://bff-service:6668/v1/api/doc_status_init
      MODEL_PROVIDER_URL: http://bff-service:6668
      REPLACE_MINIO_DOWNLOAD_URL: ${WANWU_WEB_BASE_URL}/minio/download/api/
    command: /model_extend/start.sh

  # ------ middleware ------

  kibana:
    restart: always
    image: ${WANWU_KIBANA_IMAGE}
    container_name: ${WANWU_KIBANA_HOST}
    networks:
      - ${WANWU_DOCKER_NETWORK}
    ports:
      - 5601:5601
    volumes:
      - wanwu_es_certs:/usr/share/kibana/config/certs
      # - wanwu_kibana_data:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es:9200
      - ELASTICSEARCH_USERNAME=${WANWU_KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD=${WANWU_KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: 4294967296 # 4GB
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 15s
      timeout: 5s
      retries: 99
      start_period: 10s

networks:
  wanwu-net:
    external: true

volumes:
  # wanwu_kibana_data:
  wanwu_es_certs:
  wanwu_shared_data_wga_sandbox_rag: