server:
  host: bff-service
  port: 6668
  web_base_url: http://localhost:8081
  api_base_url: http://localhost:6668
  app_open_base_url: http://localhost:6668
  callback_url: http://bff-service:6668

log:
  std: true
  level: debug
  logs:
    - enable: true
      filename: log/bff-info.log
      level: info
      max_size: 10
      max_backups: 10
      max_age: 30
    - enable: true
      filename: log/bff-err.log
      level: error
      max_size: 10
      max_backups: 10
      max_age: 30

jwt:
  signing-key:

oauth:
  switch:
  rsa:
    private_key_path: /app/tmp/oauth_rsa_private.pem
    public_key_path: /app/tmp/oauth_rsa_public.pem

decrypt-passwd:
  iv: "sdf4ddfsFD86Vdf2"
  key: "f5Su3GhNMM1rndyp"

i18n:
  type: jsonl
  xlsxPath: configs/microservice/bff-service/configs/wanwu-i18n.xlsx
  xlsxSheets:
    - bff-service
    - bff-custom
    - iam-service
    - model-service
    - knowledge-service
    - mcp-service
    - rag-service
    - assistant-service
    - app-service
    - operate-service
  jsonlPath: configs/microservice/bff-service/configs/wanwu-i18n.jsonl
  langs:
    - code: zh
      name: 中文
    - code: en
      name: English
  defaultLang: zh

assistant-template:
  configPath: configs/microservice/bff-service/configs/assistant_template_config.yaml

custom-info:
  default_mode: light
  modes:
    - mode: light
      login:
        background_path: "/v1/static/logo/login_bg.jpg"
        logo_path: "/v1/static/logo/login_logo.png"
        login_button_color: "#384BF7"
        welcome_text: bff_custom_login_welcome_text
        platform_desc: bff_custom_login_platform_desc
      home:
        logo_path: "/v1/static/logo/title_logo.png"
        title: bff_custom_home_title
        background_color: "linear-gradient(1deg,#fff 42%,#fff 0,#ebedfe 98%,#eef0ff 0)"
      tab:
        title: bff_custom_tab_title
        logo_path: "/v1/static/logo/tab_logo.png"
      about:
        logo_path: "/v1/static/logo/about_logo.png"
        copyright: bff_custom_about_copyright
    - mode: dark
  version: v0.1.0
  register_by_email: 0
  reset_password_by_email: 0
  login_by_email: 0

default-icon:
  user: "/v1/static/icon/user-default-icon.png"
  rag: "/v1/static/icon/rag-default-icon.png"
  agent: "/v1/static/icon/agent-default-icon.png"
  workflow: "/v1/static/icon/workflow-default-icon.png"
  chatflow: "/v1/static/icon/chatflow-default-icon.png"
  mcpCustom: "/v1/static/icon/mcp-custom-default-icon.png"
  mcpServer: "/v1/static/icon/mcp-server-default-icon.png"
  tool: "/v1/static/icon/custom-tool-default-icon.png"
  prompt: "/v1/static/icon/prompt-default-icon.png"
  skill: "/v1/static/icon/skill-default-icon.png"

doc-center:
  frontend_prefix: /aibase/docCenter/pages
  links:
    - key: api-rag
      val: wanwu-openapi/1.文本问答API.md
    - key: api-agent
      val: wanwu-openapi/2.智能体API.md
    - key: api-workflow
      val: wanwu-openapi/3.工作流API.md
    - key: model
      val: 模型导入方式-详细版.md
    - key: knowledge
      val: 2.资源库/知识库/创建知识库、问答库/创建内部知识库.md
    - key: knowledge-hit
      val: 2.资源库/知识库/命中测试/创建命中测试.md
    - key: knowledge-keywords
      val: 2.资源库/知识库/关键词管理.md
    - key: mcp
      val: 2.资源库/MCP服务.md
    - key: safety
      val: 2.资源库/安全护栏.md
    - key: rag
      val: 3.应用开发/文本问答.md
    - key: agent
      val: 3.应用开发/智能体.md
    - key: workflow-1
      val: 3.应用开发/工作流/开始节点.md
    - key: workflow-2
      val: 3.应用开发/工作流/结束节点.md
    - key: workflow-3
      val: 3.应用开发/工作流/大模型节点.md
    - key: workflow-5
      val: 3.应用开发/工作流/业务逻辑/代码节点.md
    - key: workflow-8
      val: 3.应用开发/工作流/业务逻辑/选择器节点.md
    - key: workflow-9
      val: 3.应用开发/工作流/工作流节点.md
    - key: workflow-12
      val: 3.应用开发/工作流/数据库/SQL自定义节点.md
    - key: workflow-13
      val: 3.应用开发/工作流/输入&输出/输出节点.md
    - key: workflow-15
      val: 3.应用开发/工作流/组件/文本处理节点.md
    - key: workflow-21
      val: 3.应用开发/工作流/业务逻辑/循环节点.md
    - key: workflow-28
      val: 3.应用开发/工作流/业务逻辑/批处理节点.md
    - key: workflow-30
      val: 3.应用开发/工作流/输入&输出/输入节点.md
    - key: workflow-32
      val: 3.应用开发/工作流/业务逻辑/变量聚合节点.md
    - key: workflow-45
      val: 3.应用开发/工作流/组件/HTTP请求节点.md
    - key: workflow-58
      val: 3.应用开发/工作流/组件/JSON序列化节点.md
    - key: workflow-1004
      val: 3.应用开发/工作流/组件/工具节点.md
    - key: workflow-1005
      val: 3.应用开发/工作流/知识库&数据/问答库检索节点.md
    - key: workflow-1006
      val: 3.应用开发/工作流/知识库&数据/知识库节点.md
    - key: workflow-1007
      val: 3.应用开发/工作流/文档/文档生成节点.md
    - key: workflow-1008
      val: 3.应用开发/工作流/文档/文档解析节点.md
    - key: workflow-1009
      val: 3.应用开发/工作流/组件/MCP节点.md
    - key: workflow-1010
      val: 3.应用开发/工作流/组件/GUI节点.md
    - key: workflow-1022
      val: 3.应用开发/工作流/业务逻辑/意图识别节点.md
    - key: workflow-1059
      val: 3.应用开发/工作流/组件/JSON反序列化节点.md

models:
  - model_id: "Asr"
    model_type: "asr"
    provider: "YuanJing"
    endpoint: "https://maas-api.ai-yuanjing.com/openapi/synchronous/asr/audio/file/transfer/unicom/sync/file/asr"

workflow-template:
  server_mode: local
  configPath: configs/microservice/bff-service/configs/workflow_template_config.yaml
  global_web_list_url:
  list_url:
  download_url:
  detail_url:
  recommend_url:

prompt-template:
  configPath: configs/microservice/bff-service/configs/prompt_template_config.yaml

skills-template:
  configPath: configs/microservice/bff-service/configs/skills_template_config.yaml
# --- middleware ---

minio:
  endpoint: localhost:9000
  user: root
  password: Wanwu123456

redis:
  host: localhost
  port: 6379
  username:
  password: Wanwu123456
  standalone: true
  master_name: mymaster

# --- microservice ---

iam:
  host: iam-service:8888

app:
  host: app-service:9988

model:
  host: model-service:8989
  png_test_file_path: "configs/microservice/bff-service/static/model/test.png"
  pdf_test_file_path: "configs/microservice/bff-service/static/model/test.pdf"
  asr_test_file_path: "configs/microservice/bff-service/static/model/test.wav"

mcp:
  host: mcp-service:9898

rag:
  host: rag-service:9640

assistant:
  host: assistant-service:8890

knowledge:
  host: knowledge-service:8889

operate:
  host: operate-service:9797

rag-knowledge:
  endpoint: 'http://rag-wanwu:8681'
  chat-endpoint: 'http://rag-wanwu:10891'
  upload-endpoint: 'http://rag-wanwu:15000'
  search-knowledge-base-uri: '/rag/search-knowledge-base'
  knowledge-chat-uri: '/rag/knowledge/stream/search'
  search-qa-base-uri: '/rag/search-QA-base'
  search-know-timeout: 300
  upload-uri: '/upload'
  upload-bucket: 'rag-public'
  upload-timeout: 120

dify-knowledge:
  search-knowledge-base-uri: '/datasets/{dataset_id}/retrieve'
  search-know-timeout: 60

workflow:
  endpoint: http://workflow-wanwu:8999
  minio_proxy_endpoint: http://workflow-wanwu:8998
  minio_proxy_prefix: /workflow/minio/presign
  # general
  list_uri: /api/workflow_api/workflow_list_by_wanwu
  create_uri: /api/workflow_api/create
  delete_uri: /api/workflow_api/delete
  copy_uri: /api/workflow_api/copy
  export_uri: /api/workflow_api/export
  import_uri: /api/workflow_api/import
  convert_uri: /api/workflow_api/update_meta_by_wanwu
  # run
  workflow_run_by_openapi_uri: /v1/workflow/%v/run_by_wanwu
  workflow_run_latest_version_uri: /v1/workflow/run_by_wanwu
  get_process_uri: /api/workflow_api/get_process
  chatflow_run_by_openapi_uri: /v1/workflow/chat_by_wanwu
  # conversation
  create_chatflow_conversation_uri: /v1/workflow/conversation/create_by_wanwu
  get_draft_intelligence_list_uri: /api/intelligence_api/search/get_draft_intelligence_list
  get_draft_intelligence_info_uri: /api/intelligence_api/search/get_draft_intelligence_info
  get_project_conversation_def: /api/workflow_api/project_conversation/create_by_wanwu
  get_conversation_message_list_uri: /v1/conversation/message/list_by_wanwu
  delete_conversation_uri: /api/workflow_api/project_conversation/delete_by_wanwu
  # upload
  upload_action_uri: /api/common/upload/apply_upload_action
  upload_common_uri: /api/common/upload
  upload_file_uri: /api/bot/upload_file_by_wanwu
  sign_img_uri: /api/workflow_api/sign_image_url
  # version
  publish_uri: /api/workflow_api/publish
  version_list_uri: /api/workflow_api/version_list
  update_version_desc_uri: /api/workflow_api/version_description
  rollback_uri: /api/workflow_api/revert
  # model params
  model_params:
    - name: temperature
      desc: "- **temperature**: 调高温度会使得模型的输出更多样性和创新性，反之，降低温度会使输出内容更加遵循指令要求但减少多样性。建议不要与“Top p”同时调整。"
      label: "生成随机性"
      type: 1
      precision: 2
      min: "0"
      max: "2"
      param_class:
        class_id: 1
        label: "生成多样性"
      default_val:
        precise: "0.3"
        balance: "0.8"
        creative: "1"
        default_val: "1"
    - name: top_p
      desc: "- **Top p 为累计概率**: 模型在生成输出时会从概率最高的词汇开始选择，直到这些词汇的总概率累积达到Top p 值。这样可以限制模型只选择这些高概率的词汇，从而控制输出内容的多样性。建议不要与“生成随机性”同时调整。"
      label: "Top P"
      type: 1
      precision: 2
      min: "0"
      max: "1"
      param_class:
        class_id: 1
        label: "生成多样性"
      default_val:
        precise: "1"
        balance: "1"
        creative: "1"
        default_val: "0.7"
    - name: frequency_penalty
      desc: "- **frequency penalty**: 当该值为正时，会阻止模型频繁使用相同的词汇和短语，从而增加输出内容的多样性。"
      label: "重复语句惩罚"
      type: 1
      precision: 2
      min: "-2"
      max: "2"
      param_class:
        class_id: 1
        label: "生成多样性"
      default_val:
        precise: "2"
        balance: "0"
        creative: "0"
        default_val: "0"
    - name: max_tokens
      desc: "控制模型输出的Tokens 长度上限。通常 100 Tokens 约等于 150 个中文汉字。"
      label: "最大回复长度"
      type: 2
      precision: 0
      min: "0"
      max: "16384"
      param_class:
        class_id: 2
        label: "输入及输出设置"
      default_val:
        default_val: "4096"
    - name: response_format
      desc: "- **文本**: 使用普通文本格式回复\n- **Markdown**: 将引导模型使用Markdown格式输出回复\n- **JSON**: 将引导模型使用JSON格式输出"
      label: "输出格式"
      type: 2
      precision: 0
      min: ""
      max: ""
      param_class:
        class_id: 2
        label: "输入及输出设置"
      default_val:
        default_val: "0"
