// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/mcp-service/mcp-service.proto

package mcp_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCPService_GetSquareMCP_FullMethodName                    = "/mcp_service.MCPService/GetSquareMCP"
	MCPService_GetSquareMCPList_FullMethodName                = "/mcp_service.MCPService/GetSquareMCPList"
	MCPService_CreateCustomMCP_FullMethodName                 = "/mcp_service.MCPService/CreateCustomMCP"
	MCPService_UpdateCustomMCP_FullMethodName                 = "/mcp_service.MCPService/UpdateCustomMCP"
	MCPService_GetCustomMCP_FullMethodName                    = "/mcp_service.MCPService/GetCustomMCP"
	MCPService_DeleteCustomMCP_FullMethodName                 = "/mcp_service.MCPService/DeleteCustomMCP"
	MCPService_GetCustomMCPList_FullMethodName                = "/mcp_service.MCPService/GetCustomMCPList"
	MCPService_GetMCPToolList_FullMethodName                  = "/mcp_service.MCPService/GetMCPToolList"
	MCPService_GetMCPAvatar_FullMethodName                    = "/mcp_service.MCPService/GetMCPAvatar"
	MCPService_CreateCustomTool_FullMethodName                = "/mcp_service.MCPService/CreateCustomTool"
	MCPService_GetCustomToolInfo_FullMethodName               = "/mcp_service.MCPService/GetCustomToolInfo"
	MCPService_GetCustomToolList_FullMethodName               = "/mcp_service.MCPService/GetCustomToolList"
	MCPService_GetCustomToolByCustomToolIdList_FullMethodName = "/mcp_service.MCPService/GetCustomToolByCustomToolIdList"
	MCPService_UpdateCustomTool_FullMethodName                = "/mcp_service.MCPService/UpdateCustomTool"
	MCPService_DeleteCustomTool_FullMethodName                = "/mcp_service.MCPService/DeleteCustomTool"
	MCPService_GetSquareTool_FullMethodName                   = "/mcp_service.MCPService/GetSquareTool"
	MCPService_GetSquareToolList_FullMethodName               = "/mcp_service.MCPService/GetSquareToolList"
	MCPService_UpsertBuiltinToolAPIKey_FullMethodName         = "/mcp_service.MCPService/UpsertBuiltinToolAPIKey"
	MCPService_CreateMCPServer_FullMethodName                 = "/mcp_service.MCPService/CreateMCPServer"
	MCPService_DeleteMCPServer_FullMethodName                 = "/mcp_service.MCPService/DeleteMCPServer"
	MCPService_UpdateMCPServer_FullMethodName                 = "/mcp_service.MCPService/UpdateMCPServer"
	MCPService_GetMCPServer_FullMethodName                    = "/mcp_service.MCPService/GetMCPServer"
	MCPService_GetMCPServerList_FullMethodName                = "/mcp_service.MCPService/GetMCPServerList"
	MCPService_CreateMCPServerTool_FullMethodName             = "/mcp_service.MCPService/CreateMCPServerTool"
	MCPService_UpdateMCPServerTool_FullMethodName             = "/mcp_service.MCPService/UpdateMCPServerTool"
	MCPService_DeleteMCPServerTool_FullMethodName             = "/mcp_service.MCPService/DeleteMCPServerTool"
	MCPService_GetMCPServerTool_FullMethodName                = "/mcp_service.MCPService/GetMCPServerTool"
	MCPService_GetMCPServerToolList_FullMethodName            = "/mcp_service.MCPService/GetMCPServerToolList"
	MCPService_GetToolSelect_FullMethodName                   = "/mcp_service.MCPService/GetToolSelect"
	MCPService_GetToolByIdList_FullMethodName                 = "/mcp_service.MCPService/GetToolByIdList"
	MCPService_GetToolDetailByIdList_FullMethodName           = "/mcp_service.MCPService/GetToolDetailByIdList"
	MCPService_GetMCPByMCPIdList_FullMethodName               = "/mcp_service.MCPService/GetMCPByMCPIdList"
	MCPService_CustomSkillCreate_FullMethodName               = "/mcp_service.MCPService/CustomSkillCreate"
	MCPService_CustomSkillDelete_FullMethodName               = "/mcp_service.MCPService/CustomSkillDelete"
	MCPService_CustomSkillGet_FullMethodName                  = "/mcp_service.MCPService/CustomSkillGet"
	MCPService_CustomSkillGetList_FullMethodName              = "/mcp_service.MCPService/CustomSkillGetList"
	MCPService_CustomSkillGetBySaveIds_FullMethodName         = "/mcp_service.MCPService/CustomSkillGetBySaveIds"
)

// MCPServiceClient is the client API for MCPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MCPServiceClient interface {
	// --- square mcp ---
	GetSquareMCP(ctx context.Context, in *GetSquareMCPReq, opts ...grpc.CallOption) (*SquareMCPDetail, error)
	GetSquareMCPList(ctx context.Context, in *GetSquareMCPListReq, opts ...grpc.CallOption) (*SquareMCPList, error)
	// --- custom mcp ---
	CreateCustomMCP(ctx context.Context, in *CreateCustomMCPReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateCustomMCP(ctx context.Context, in *UpdateCustomMCPReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCustomMCP(ctx context.Context, in *GetCustomMCPReq, opts ...grpc.CallOption) (*CustomMCPDetail, error)
	DeleteCustomMCP(ctx context.Context, in *DeleteCustomMCPReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCustomMCPList(ctx context.Context, in *GetCustomMCPListReq, opts ...grpc.CallOption) (*CustomMCPList, error)
	// --- custom mcp action ---
	GetMCPToolList(ctx context.Context, in *GetMCPToolListReq, opts ...grpc.CallOption) (*MCPToolList, error)
	GetMCPAvatar(ctx context.Context, in *GetMCPAvatarReq, opts ...grpc.CallOption) (*MCPAvatar, error)
	// --- custom tool ---
	CreateCustomTool(ctx context.Context, in *CreateCustomToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCustomToolInfo(ctx context.Context, in *GetCustomToolInfoReq, opts ...grpc.CallOption) (*GetCustomToolInfoResp, error)
	GetCustomToolList(ctx context.Context, in *GetCustomToolListReq, opts ...grpc.CallOption) (*GetCustomToolListResp, error)
	GetCustomToolByCustomToolIdList(ctx context.Context, in *GetCustomToolByCustomToolIdListReq, opts ...grpc.CallOption) (*GetCustomToolListResp, error)
	UpdateCustomTool(ctx context.Context, in *UpdateCustomToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteCustomTool(ctx context.Context, in *DeleteCustomToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- builtin tool ---
	GetSquareTool(ctx context.Context, in *GetSquareToolReq, opts ...grpc.CallOption) (*SquareToolDetail, error)
	GetSquareToolList(ctx context.Context, in *GetSquareToolListReq, opts ...grpc.CallOption) (*SquareToolList, error)
	UpsertBuiltinToolAPIKey(ctx context.Context, in *UpsertBuiltinToolAPIKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- mcp server ---
	CreateMCPServer(ctx context.Context, in *CreateMCPServerReq, opts ...grpc.CallOption) (*CreateMCPServerResp, error)
	DeleteMCPServer(ctx context.Context, in *DeleteMCPServerReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateMCPServer(ctx context.Context, in *UpdateMCPServerReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMCPServer(ctx context.Context, in *GetMCPServerReq, opts ...grpc.CallOption) (*MCPServerInfo, error)
	GetMCPServerList(ctx context.Context, in *GetMCPServerListReq, opts ...grpc.CallOption) (*GetMCPServerListResp, error)
	CreateMCPServerTool(ctx context.Context, in *CreateMCPServerToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateMCPServerTool(ctx context.Context, in *UpdateMCPServerToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteMCPServerTool(ctx context.Context, in *DeleteMCPServerToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMCPServerTool(ctx context.Context, in *GetMCPServerToolReq, opts ...grpc.CallOption) (*MCPServerToolInfo, error)
	GetMCPServerToolList(ctx context.Context, in *GetMCPServerToolListReq, opts ...grpc.CallOption) (*GetMCPServerToolListResp, error)
	// --- custom builtin tool ---
	GetToolSelect(ctx context.Context, in *GetToolSelectReq, opts ...grpc.CallOption) (*GetToolListResp, error)
	GetToolByIdList(ctx context.Context, in *GetToolByToolIdListReq, opts ...grpc.CallOption) (*GetToolByToolIdListResp, error)
	GetToolDetailByIdList(ctx context.Context, in *GetToolByToolIdListReq, opts ...grpc.CallOption) (*GetToolDetailByToolIdListResp, error)
	// --- mcp mcpserver tool ---
	GetMCPByMCPIdList(ctx context.Context, in *GetMCPByMCPIdListReq, opts ...grpc.CallOption) (*GetMCPByMCPIdListResp, error)
	// --- custom skill ---
	CustomSkillCreate(ctx context.Context, in *CustomSkillCreateReq, opts ...grpc.CallOption) (*CustomSkillCreateResp, error)
	CustomSkillDelete(ctx context.Context, in *CustomSkillDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CustomSkillGet(ctx context.Context, in *CustomSkillGetReq, opts ...grpc.CallOption) (*CustomSkill, error)
	CustomSkillGetList(ctx context.Context, in *CustomSkillGetListReq, opts ...grpc.CallOption) (*CustomSkillGetListResp, error)
	CustomSkillGetBySaveIds(ctx context.Context, in *CustomSkillGetBySaveIdsReq, opts ...grpc.CallOption) (*CustomSkillSaveIdsResp, error)
}

type mCPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPServiceClient(cc grpc.ClientConnInterface) MCPServiceClient {
	return &mCPServiceClient{cc}
}

func (c *mCPServiceClient) GetSquareMCP(ctx context.Context, in *GetSquareMCPReq, opts ...grpc.CallOption) (*SquareMCPDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SquareMCPDetail)
	err := c.cc.Invoke(ctx, MCPService_GetSquareMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetSquareMCPList(ctx context.Context, in *GetSquareMCPListReq, opts ...grpc.CallOption) (*SquareMCPList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SquareMCPList)
	err := c.cc.Invoke(ctx, MCPService_GetSquareMCPList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CreateCustomMCP(ctx context.Context, in *CreateCustomMCPReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_CreateCustomMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) UpdateCustomMCP(ctx context.Context, in *UpdateCustomMCPReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_UpdateCustomMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetCustomMCP(ctx context.Context, in *GetCustomMCPReq, opts ...grpc.CallOption) (*CustomMCPDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomMCPDetail)
	err := c.cc.Invoke(ctx, MCPService_GetCustomMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) DeleteCustomMCP(ctx context.Context, in *DeleteCustomMCPReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_DeleteCustomMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetCustomMCPList(ctx context.Context, in *GetCustomMCPListReq, opts ...grpc.CallOption) (*CustomMCPList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomMCPList)
	err := c.cc.Invoke(ctx, MCPService_GetCustomMCPList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetMCPToolList(ctx context.Context, in *GetMCPToolListReq, opts ...grpc.CallOption) (*MCPToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPToolList)
	err := c.cc.Invoke(ctx, MCPService_GetMCPToolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetMCPAvatar(ctx context.Context, in *GetMCPAvatarReq, opts ...grpc.CallOption) (*MCPAvatar, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPAvatar)
	err := c.cc.Invoke(ctx, MCPService_GetMCPAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CreateCustomTool(ctx context.Context, in *CreateCustomToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_CreateCustomTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetCustomToolInfo(ctx context.Context, in *GetCustomToolInfoReq, opts ...grpc.CallOption) (*GetCustomToolInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomToolInfoResp)
	err := c.cc.Invoke(ctx, MCPService_GetCustomToolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetCustomToolList(ctx context.Context, in *GetCustomToolListReq, opts ...grpc.CallOption) (*GetCustomToolListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomToolListResp)
	err := c.cc.Invoke(ctx, MCPService_GetCustomToolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetCustomToolByCustomToolIdList(ctx context.Context, in *GetCustomToolByCustomToolIdListReq, opts ...grpc.CallOption) (*GetCustomToolListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomToolListResp)
	err := c.cc.Invoke(ctx, MCPService_GetCustomToolByCustomToolIdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) UpdateCustomTool(ctx context.Context, in *UpdateCustomToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_UpdateCustomTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) DeleteCustomTool(ctx context.Context, in *DeleteCustomToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_DeleteCustomTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetSquareTool(ctx context.Context, in *GetSquareToolReq, opts ...grpc.CallOption) (*SquareToolDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SquareToolDetail)
	err := c.cc.Invoke(ctx, MCPService_GetSquareTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetSquareToolList(ctx context.Context, in *GetSquareToolListReq, opts ...grpc.CallOption) (*SquareToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SquareToolList)
	err := c.cc.Invoke(ctx, MCPService_GetSquareToolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) UpsertBuiltinToolAPIKey(ctx context.Context, in *UpsertBuiltinToolAPIKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_UpsertBuiltinToolAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CreateMCPServer(ctx context.Context, in *CreateMCPServerReq, opts ...grpc.CallOption) (*CreateMCPServerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMCPServerResp)
	err := c.cc.Invoke(ctx, MCPService_CreateMCPServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) DeleteMCPServer(ctx context.Context, in *DeleteMCPServerReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_DeleteMCPServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) UpdateMCPServer(ctx context.Context, in *UpdateMCPServerReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_UpdateMCPServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetMCPServer(ctx context.Context, in *GetMCPServerReq, opts ...grpc.CallOption) (*MCPServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPServerInfo)
	err := c.cc.Invoke(ctx, MCPService_GetMCPServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetMCPServerList(ctx context.Context, in *GetMCPServerListReq, opts ...grpc.CallOption) (*GetMCPServerListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMCPServerListResp)
	err := c.cc.Invoke(ctx, MCPService_GetMCPServerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CreateMCPServerTool(ctx context.Context, in *CreateMCPServerToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_CreateMCPServerTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) UpdateMCPServerTool(ctx context.Context, in *UpdateMCPServerToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_UpdateMCPServerTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) DeleteMCPServerTool(ctx context.Context, in *DeleteMCPServerToolReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_DeleteMCPServerTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetMCPServerTool(ctx context.Context, in *GetMCPServerToolReq, opts ...grpc.CallOption) (*MCPServerToolInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPServerToolInfo)
	err := c.cc.Invoke(ctx, MCPService_GetMCPServerTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetMCPServerToolList(ctx context.Context, in *GetMCPServerToolListReq, opts ...grpc.CallOption) (*GetMCPServerToolListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMCPServerToolListResp)
	err := c.cc.Invoke(ctx, MCPService_GetMCPServerToolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetToolSelect(ctx context.Context, in *GetToolSelectReq, opts ...grpc.CallOption) (*GetToolListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolListResp)
	err := c.cc.Invoke(ctx, MCPService_GetToolSelect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetToolByIdList(ctx context.Context, in *GetToolByToolIdListReq, opts ...grpc.CallOption) (*GetToolByToolIdListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolByToolIdListResp)
	err := c.cc.Invoke(ctx, MCPService_GetToolByIdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetToolDetailByIdList(ctx context.Context, in *GetToolByToolIdListReq, opts ...grpc.CallOption) (*GetToolDetailByToolIdListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolDetailByToolIdListResp)
	err := c.cc.Invoke(ctx, MCPService_GetToolDetailByIdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetMCPByMCPIdList(ctx context.Context, in *GetMCPByMCPIdListReq, opts ...grpc.CallOption) (*GetMCPByMCPIdListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMCPByMCPIdListResp)
	err := c.cc.Invoke(ctx, MCPService_GetMCPByMCPIdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CustomSkillCreate(ctx context.Context, in *CustomSkillCreateReq, opts ...grpc.CallOption) (*CustomSkillCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomSkillCreateResp)
	err := c.cc.Invoke(ctx, MCPService_CustomSkillCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CustomSkillDelete(ctx context.Context, in *CustomSkillDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCPService_CustomSkillDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CustomSkillGet(ctx context.Context, in *CustomSkillGetReq, opts ...grpc.CallOption) (*CustomSkill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomSkill)
	err := c.cc.Invoke(ctx, MCPService_CustomSkillGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CustomSkillGetList(ctx context.Context, in *CustomSkillGetListReq, opts ...grpc.CallOption) (*CustomSkillGetListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomSkillGetListResp)
	err := c.cc.Invoke(ctx, MCPService_CustomSkillGetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CustomSkillGetBySaveIds(ctx context.Context, in *CustomSkillGetBySaveIdsReq, opts ...grpc.CallOption) (*CustomSkillSaveIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomSkillSaveIdsResp)
	err := c.cc.Invoke(ctx, MCPService_CustomSkillGetBySaveIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCPServiceServer is the server API for MCPService service.
// All implementations must embed UnimplementedMCPServiceServer
// for forward compatibility.
type MCPServiceServer interface {
	// --- square mcp ---
	GetSquareMCP(context.Context, *GetSquareMCPReq) (*SquareMCPDetail, error)
	GetSquareMCPList(context.Context, *GetSquareMCPListReq) (*SquareMCPList, error)
	// --- custom mcp ---
	CreateCustomMCP(context.Context, *CreateCustomMCPReq) (*emptypb.Empty, error)
	UpdateCustomMCP(context.Context, *UpdateCustomMCPReq) (*emptypb.Empty, error)
	GetCustomMCP(context.Context, *GetCustomMCPReq) (*CustomMCPDetail, error)
	DeleteCustomMCP(context.Context, *DeleteCustomMCPReq) (*emptypb.Empty, error)
	GetCustomMCPList(context.Context, *GetCustomMCPListReq) (*CustomMCPList, error)
	// --- custom mcp action ---
	GetMCPToolList(context.Context, *GetMCPToolListReq) (*MCPToolList, error)
	GetMCPAvatar(context.Context, *GetMCPAvatarReq) (*MCPAvatar, error)
	// --- custom tool ---
	CreateCustomTool(context.Context, *CreateCustomToolReq) (*emptypb.Empty, error)
	GetCustomToolInfo(context.Context, *GetCustomToolInfoReq) (*GetCustomToolInfoResp, error)
	GetCustomToolList(context.Context, *GetCustomToolListReq) (*GetCustomToolListResp, error)
	GetCustomToolByCustomToolIdList(context.Context, *GetCustomToolByCustomToolIdListReq) (*GetCustomToolListResp, error)
	UpdateCustomTool(context.Context, *UpdateCustomToolReq) (*emptypb.Empty, error)
	DeleteCustomTool(context.Context, *DeleteCustomToolReq) (*emptypb.Empty, error)
	// --- builtin tool ---
	GetSquareTool(context.Context, *GetSquareToolReq) (*SquareToolDetail, error)
	GetSquareToolList(context.Context, *GetSquareToolListReq) (*SquareToolList, error)
	UpsertBuiltinToolAPIKey(context.Context, *UpsertBuiltinToolAPIKeyReq) (*emptypb.Empty, error)
	// --- mcp server ---
	CreateMCPServer(context.Context, *CreateMCPServerReq) (*CreateMCPServerResp, error)
	DeleteMCPServer(context.Context, *DeleteMCPServerReq) (*emptypb.Empty, error)
	UpdateMCPServer(context.Context, *UpdateMCPServerReq) (*emptypb.Empty, error)
	GetMCPServer(context.Context, *GetMCPServerReq) (*MCPServerInfo, error)
	GetMCPServerList(context.Context, *GetMCPServerListReq) (*GetMCPServerListResp, error)
	CreateMCPServerTool(context.Context, *CreateMCPServerToolReq) (*emptypb.Empty, error)
	UpdateMCPServerTool(context.Context, *UpdateMCPServerToolReq) (*emptypb.Empty, error)
	DeleteMCPServerTool(context.Context, *DeleteMCPServerToolReq) (*emptypb.Empty, error)
	GetMCPServerTool(context.Context, *GetMCPServerToolReq) (*MCPServerToolInfo, error)
	GetMCPServerToolList(context.Context, *GetMCPServerToolListReq) (*GetMCPServerToolListResp, error)
	// --- custom builtin tool ---
	GetToolSelect(context.Context, *GetToolSelectReq) (*GetToolListResp, error)
	GetToolByIdList(context.Context, *GetToolByToolIdListReq) (*GetToolByToolIdListResp, error)
	GetToolDetailByIdList(context.Context, *GetToolByToolIdListReq) (*GetToolDetailByToolIdListResp, error)
	// --- mcp mcpserver tool ---
	GetMCPByMCPIdList(context.Context, *GetMCPByMCPIdListReq) (*GetMCPByMCPIdListResp, error)
	// --- custom skill ---
	CustomSkillCreate(context.Context, *CustomSkillCreateReq) (*CustomSkillCreateResp, error)
	CustomSkillDelete(context.Context, *CustomSkillDeleteReq) (*emptypb.Empty, error)
	CustomSkillGet(context.Context, *CustomSkillGetReq) (*CustomSkill, error)
	CustomSkillGetList(context.Context, *CustomSkillGetListReq) (*CustomSkillGetListResp, error)
	CustomSkillGetBySaveIds(context.Context, *CustomSkillGetBySaveIdsReq) (*CustomSkillSaveIdsResp, error)
	mustEmbedUnimplementedMCPServiceServer()
}

// UnimplementedMCPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPServiceServer struct{}

func (UnimplementedMCPServiceServer) GetSquareMCP(context.Context, *GetSquareMCPReq) (*SquareMCPDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSquareMCP not implemented")
}
func (UnimplementedMCPServiceServer) GetSquareMCPList(context.Context, *GetSquareMCPListReq) (*SquareMCPList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSquareMCPList not implemented")
}
func (UnimplementedMCPServiceServer) CreateCustomMCP(context.Context, *CreateCustomMCPReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomMCP not implemented")
}
func (UnimplementedMCPServiceServer) UpdateCustomMCP(context.Context, *UpdateCustomMCPReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomMCP not implemented")
}
func (UnimplementedMCPServiceServer) GetCustomMCP(context.Context, *GetCustomMCPReq) (*CustomMCPDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomMCP not implemented")
}
func (UnimplementedMCPServiceServer) DeleteCustomMCP(context.Context, *DeleteCustomMCPReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomMCP not implemented")
}
func (UnimplementedMCPServiceServer) GetCustomMCPList(context.Context, *GetCustomMCPListReq) (*CustomMCPList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomMCPList not implemented")
}
func (UnimplementedMCPServiceServer) GetMCPToolList(context.Context, *GetMCPToolListReq) (*MCPToolList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPToolList not implemented")
}
func (UnimplementedMCPServiceServer) GetMCPAvatar(context.Context, *GetMCPAvatarReq) (*MCPAvatar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPAvatar not implemented")
}
func (UnimplementedMCPServiceServer) CreateCustomTool(context.Context, *CreateCustomToolReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomTool not implemented")
}
func (UnimplementedMCPServiceServer) GetCustomToolInfo(context.Context, *GetCustomToolInfoReq) (*GetCustomToolInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomToolInfo not implemented")
}
func (UnimplementedMCPServiceServer) GetCustomToolList(context.Context, *GetCustomToolListReq) (*GetCustomToolListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomToolList not implemented")
}
func (UnimplementedMCPServiceServer) GetCustomToolByCustomToolIdList(context.Context, *GetCustomToolByCustomToolIdListReq) (*GetCustomToolListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomToolByCustomToolIdList not implemented")
}
func (UnimplementedMCPServiceServer) UpdateCustomTool(context.Context, *UpdateCustomToolReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomTool not implemented")
}
func (UnimplementedMCPServiceServer) DeleteCustomTool(context.Context, *DeleteCustomToolReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomTool not implemented")
}
func (UnimplementedMCPServiceServer) GetSquareTool(context.Context, *GetSquareToolReq) (*SquareToolDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSquareTool not implemented")
}
func (UnimplementedMCPServiceServer) GetSquareToolList(context.Context, *GetSquareToolListReq) (*SquareToolList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSquareToolList not implemented")
}
func (UnimplementedMCPServiceServer) UpsertBuiltinToolAPIKey(context.Context, *UpsertBuiltinToolAPIKeyReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertBuiltinToolAPIKey not implemented")
}
func (UnimplementedMCPServiceServer) CreateMCPServer(context.Context, *CreateMCPServerReq) (*CreateMCPServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMCPServer not implemented")
}
func (UnimplementedMCPServiceServer) DeleteMCPServer(context.Context, *DeleteMCPServerReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMCPServer not implemented")
}
func (UnimplementedMCPServiceServer) UpdateMCPServer(context.Context, *UpdateMCPServerReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMCPServer not implemented")
}
func (UnimplementedMCPServiceServer) GetMCPServer(context.Context, *GetMCPServerReq) (*MCPServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPServer not implemented")
}
func (UnimplementedMCPServiceServer) GetMCPServerList(context.Context, *GetMCPServerListReq) (*GetMCPServerListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPServerList not implemented")
}
func (UnimplementedMCPServiceServer) CreateMCPServerTool(context.Context, *CreateMCPServerToolReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMCPServerTool not implemented")
}
func (UnimplementedMCPServiceServer) UpdateMCPServerTool(context.Context, *UpdateMCPServerToolReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMCPServerTool not implemented")
}
func (UnimplementedMCPServiceServer) DeleteMCPServerTool(context.Context, *DeleteMCPServerToolReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMCPServerTool not implemented")
}
func (UnimplementedMCPServiceServer) GetMCPServerTool(context.Context, *GetMCPServerToolReq) (*MCPServerToolInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPServerTool not implemented")
}
func (UnimplementedMCPServiceServer) GetMCPServerToolList(context.Context, *GetMCPServerToolListReq) (*GetMCPServerToolListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPServerToolList not implemented")
}
func (UnimplementedMCPServiceServer) GetToolSelect(context.Context, *GetToolSelectReq) (*GetToolListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolSelect not implemented")
}
func (UnimplementedMCPServiceServer) GetToolByIdList(context.Context, *GetToolByToolIdListReq) (*GetToolByToolIdListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolByIdList not implemented")
}
func (UnimplementedMCPServiceServer) GetToolDetailByIdList(context.Context, *GetToolByToolIdListReq) (*GetToolDetailByToolIdListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolDetailByIdList not implemented")
}
func (UnimplementedMCPServiceServer) GetMCPByMCPIdList(context.Context, *GetMCPByMCPIdListReq) (*GetMCPByMCPIdListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPByMCPIdList not implemented")
}
func (UnimplementedMCPServiceServer) CustomSkillCreate(context.Context, *CustomSkillCreateReq) (*CustomSkillCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomSkillCreate not implemented")
}
func (UnimplementedMCPServiceServer) CustomSkillDelete(context.Context, *CustomSkillDeleteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomSkillDelete not implemented")
}
func (UnimplementedMCPServiceServer) CustomSkillGet(context.Context, *CustomSkillGetReq) (*CustomSkill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomSkillGet not implemented")
}
func (UnimplementedMCPServiceServer) CustomSkillGetList(context.Context, *CustomSkillGetListReq) (*CustomSkillGetListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomSkillGetList not implemented")
}
func (UnimplementedMCPServiceServer) CustomSkillGetBySaveIds(context.Context, *CustomSkillGetBySaveIdsReq) (*CustomSkillSaveIdsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomSkillGetBySaveIds not implemented")
}
func (UnimplementedMCPServiceServer) mustEmbedUnimplementedMCPServiceServer() {}
func (UnimplementedMCPServiceServer) testEmbeddedByValue()                    {}

// UnsafeMCPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPServiceServer will
// result in compilation errors.
type UnsafeMCPServiceServer interface {
	mustEmbedUnimplementedMCPServiceServer()
}

func RegisterMCPServiceServer(s grpc.ServiceRegistrar, srv MCPServiceServer) {
	// If the following call pancis, it indicates UnimplementedMCPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPService_ServiceDesc, srv)
}

func _MCPService_GetSquareMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSquareMCPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetSquareMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetSquareMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetSquareMCP(ctx, req.(*GetSquareMCPReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetSquareMCPList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSquareMCPListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetSquareMCPList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetSquareMCPList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetSquareMCPList(ctx, req.(*GetSquareMCPListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CreateCustomMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomMCPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CreateCustomMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CreateCustomMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CreateCustomMCP(ctx, req.(*CreateCustomMCPReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_UpdateCustomMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomMCPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).UpdateCustomMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_UpdateCustomMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).UpdateCustomMCP(ctx, req.(*UpdateCustomMCPReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetCustomMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomMCPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetCustomMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetCustomMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetCustomMCP(ctx, req.(*GetCustomMCPReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_DeleteCustomMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomMCPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).DeleteCustomMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_DeleteCustomMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).DeleteCustomMCP(ctx, req.(*DeleteCustomMCPReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetCustomMCPList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomMCPListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetCustomMCPList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetCustomMCPList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetCustomMCPList(ctx, req.(*GetCustomMCPListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetMCPToolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPToolListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetMCPToolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetMCPToolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetMCPToolList(ctx, req.(*GetMCPToolListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetMCPAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPAvatarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetMCPAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetMCPAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetMCPAvatar(ctx, req.(*GetMCPAvatarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CreateCustomTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CreateCustomTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CreateCustomTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CreateCustomTool(ctx, req.(*CreateCustomToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetCustomToolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomToolInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetCustomToolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetCustomToolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetCustomToolInfo(ctx, req.(*GetCustomToolInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetCustomToolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomToolListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetCustomToolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetCustomToolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetCustomToolList(ctx, req.(*GetCustomToolListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetCustomToolByCustomToolIdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomToolByCustomToolIdListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetCustomToolByCustomToolIdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetCustomToolByCustomToolIdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetCustomToolByCustomToolIdList(ctx, req.(*GetCustomToolByCustomToolIdListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_UpdateCustomTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).UpdateCustomTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_UpdateCustomTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).UpdateCustomTool(ctx, req.(*UpdateCustomToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_DeleteCustomTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).DeleteCustomTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_DeleteCustomTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).DeleteCustomTool(ctx, req.(*DeleteCustomToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetSquareTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSquareToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetSquareTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetSquareTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetSquareTool(ctx, req.(*GetSquareToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetSquareToolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSquareToolListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetSquareToolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetSquareToolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetSquareToolList(ctx, req.(*GetSquareToolListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_UpsertBuiltinToolAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertBuiltinToolAPIKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).UpsertBuiltinToolAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_UpsertBuiltinToolAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).UpsertBuiltinToolAPIKey(ctx, req.(*UpsertBuiltinToolAPIKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CreateMCPServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMCPServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CreateMCPServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CreateMCPServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CreateMCPServer(ctx, req.(*CreateMCPServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_DeleteMCPServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMCPServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).DeleteMCPServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_DeleteMCPServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).DeleteMCPServer(ctx, req.(*DeleteMCPServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_UpdateMCPServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMCPServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).UpdateMCPServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_UpdateMCPServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).UpdateMCPServer(ctx, req.(*UpdateMCPServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetMCPServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetMCPServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetMCPServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetMCPServer(ctx, req.(*GetMCPServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetMCPServerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPServerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetMCPServerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetMCPServerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetMCPServerList(ctx, req.(*GetMCPServerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CreateMCPServerTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMCPServerToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CreateMCPServerTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CreateMCPServerTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CreateMCPServerTool(ctx, req.(*CreateMCPServerToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_UpdateMCPServerTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMCPServerToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).UpdateMCPServerTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_UpdateMCPServerTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).UpdateMCPServerTool(ctx, req.(*UpdateMCPServerToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_DeleteMCPServerTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMCPServerToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).DeleteMCPServerTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_DeleteMCPServerTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).DeleteMCPServerTool(ctx, req.(*DeleteMCPServerToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetMCPServerTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPServerToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetMCPServerTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetMCPServerTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetMCPServerTool(ctx, req.(*GetMCPServerToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetMCPServerToolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPServerToolListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetMCPServerToolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetMCPServerToolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetMCPServerToolList(ctx, req.(*GetMCPServerToolListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetToolSelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetToolSelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetToolSelect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetToolSelect(ctx, req.(*GetToolSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetToolByIdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolByToolIdListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetToolByIdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetToolByIdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetToolByIdList(ctx, req.(*GetToolByToolIdListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetToolDetailByIdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolByToolIdListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetToolDetailByIdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetToolDetailByIdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetToolDetailByIdList(ctx, req.(*GetToolByToolIdListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetMCPByMCPIdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPByMCPIdListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetMCPByMCPIdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetMCPByMCPIdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetMCPByMCPIdList(ctx, req.(*GetMCPByMCPIdListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CustomSkillCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomSkillCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CustomSkillCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CustomSkillCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CustomSkillCreate(ctx, req.(*CustomSkillCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CustomSkillDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomSkillDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CustomSkillDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CustomSkillDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CustomSkillDelete(ctx, req.(*CustomSkillDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CustomSkillGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomSkillGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CustomSkillGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CustomSkillGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CustomSkillGet(ctx, req.(*CustomSkillGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CustomSkillGetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomSkillGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CustomSkillGetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CustomSkillGetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CustomSkillGetList(ctx, req.(*CustomSkillGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CustomSkillGetBySaveIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomSkillGetBySaveIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CustomSkillGetBySaveIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CustomSkillGetBySaveIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CustomSkillGetBySaveIds(ctx, req.(*CustomSkillGetBySaveIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MCPService_ServiceDesc is the grpc.ServiceDesc for MCPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp_service.MCPService",
	HandlerType: (*MCPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSquareMCP",
			Handler:    _MCPService_GetSquareMCP_Handler,
		},
		{
			MethodName: "GetSquareMCPList",
			Handler:    _MCPService_GetSquareMCPList_Handler,
		},
		{
			MethodName: "CreateCustomMCP",
			Handler:    _MCPService_CreateCustomMCP_Handler,
		},
		{
			MethodName: "UpdateCustomMCP",
			Handler:    _MCPService_UpdateCustomMCP_Handler,
		},
		{
			MethodName: "GetCustomMCP",
			Handler:    _MCPService_GetCustomMCP_Handler,
		},
		{
			MethodName: "DeleteCustomMCP",
			Handler:    _MCPService_DeleteCustomMCP_Handler,
		},
		{
			MethodName: "GetCustomMCPList",
			Handler:    _MCPService_GetCustomMCPList_Handler,
		},
		{
			MethodName: "GetMCPToolList",
			Handler:    _MCPService_GetMCPToolList_Handler,
		},
		{
			MethodName: "GetMCPAvatar",
			Handler:    _MCPService_GetMCPAvatar_Handler,
		},
		{
			MethodName: "CreateCustomTool",
			Handler:    _MCPService_CreateCustomTool_Handler,
		},
		{
			MethodName: "GetCustomToolInfo",
			Handler:    _MCPService_GetCustomToolInfo_Handler,
		},
		{
			MethodName: "GetCustomToolList",
			Handler:    _MCPService_GetCustomToolList_Handler,
		},
		{
			MethodName: "GetCustomToolByCustomToolIdList",
			Handler:    _MCPService_GetCustomToolByCustomToolIdList_Handler,
		},
		{
			MethodName: "UpdateCustomTool",
			Handler:    _MCPService_UpdateCustomTool_Handler,
		},
		{
			MethodName: "DeleteCustomTool",
			Handler:    _MCPService_DeleteCustomTool_Handler,
		},
		{
			MethodName: "GetSquareTool",
			Handler:    _MCPService_GetSquareTool_Handler,
		},
		{
			MethodName: "GetSquareToolList",
			Handler:    _MCPService_GetSquareToolList_Handler,
		},
		{
			MethodName: "UpsertBuiltinToolAPIKey",
			Handler:    _MCPService_UpsertBuiltinToolAPIKey_Handler,
		},
		{
			MethodName: "CreateMCPServer",
			Handler:    _MCPService_CreateMCPServer_Handler,
		},
		{
			MethodName: "DeleteMCPServer",
			Handler:    _MCPService_DeleteMCPServer_Handler,
		},
		{
			MethodName: "UpdateMCPServer",
			Handler:    _MCPService_UpdateMCPServer_Handler,
		},
		{
			MethodName: "GetMCPServer",
			Handler:    _MCPService_GetMCPServer_Handler,
		},
		{
			MethodName: "GetMCPServerList",
			Handler:    _MCPService_GetMCPServerList_Handler,
		},
		{
			MethodName: "CreateMCPServerTool",
			Handler:    _MCPService_CreateMCPServerTool_Handler,
		},
		{
			MethodName: "UpdateMCPServerTool",
			Handler:    _MCPService_UpdateMCPServerTool_Handler,
		},
		{
			MethodName: "DeleteMCPServerTool",
			Handler:    _MCPService_DeleteMCPServerTool_Handler,
		},
		{
			MethodName: "GetMCPServerTool",
			Handler:    _MCPService_GetMCPServerTool_Handler,
		},
		{
			MethodName: "GetMCPServerToolList",
			Handler:    _MCPService_GetMCPServerToolList_Handler,
		},
		{
			MethodName: "GetToolSelect",
			Handler:    _MCPService_GetToolSelect_Handler,
		},
		{
			MethodName: "GetToolByIdList",
			Handler:    _MCPService_GetToolByIdList_Handler,
		},
		{
			MethodName: "GetToolDetailByIdList",
			Handler:    _MCPService_GetToolDetailByIdList_Handler,
		},
		{
			MethodName: "GetMCPByMCPIdList",
			Handler:    _MCPService_GetMCPByMCPIdList_Handler,
		},
		{
			MethodName: "CustomSkillCreate",
			Handler:    _MCPService_CustomSkillCreate_Handler,
		},
		{
			MethodName: "CustomSkillDelete",
			Handler:    _MCPService_CustomSkillDelete_Handler,
		},
		{
			MethodName: "CustomSkillGet",
			Handler:    _MCPService_CustomSkillGet_Handler,
		},
		{
			MethodName: "CustomSkillGetList",
			Handler:    _MCPService_CustomSkillGetList_Handler,
		},
		{
			MethodName: "CustomSkillGetBySaveIds",
			Handler:    _MCPService_CustomSkillGetBySaveIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mcp-service/mcp-service.proto",
}
