// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/app-service/app-service.proto

package app_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppService_CreateApiKey_FullMethodName                 = "/app_service.AppService/CreateApiKey"
	AppService_DeleteApiKey_FullMethodName                 = "/app_service.AppService/DeleteApiKey"
	AppService_ListApiKeys_FullMethodName                  = "/app_service.AppService/ListApiKeys"
	AppService_UpdateApiKey_FullMethodName                 = "/app_service.AppService/UpdateApiKey"
	AppService_UpdateApiKeyStatus_FullMethodName           = "/app_service.AppService/UpdateApiKeyStatus"
	AppService_GetApiKeyByKey_FullMethodName               = "/app_service.AppService/GetApiKeyByKey"
	AppService_GenAppKey_FullMethodName                    = "/app_service.AppService/GenAppKey"
	AppService_GetAppKeyList_FullMethodName                = "/app_service.AppService/GetAppKeyList"
	AppService_DelAppKey_FullMethodName                    = "/app_service.AppService/DelAppKey"
	AppService_GetAppKeyByKey_FullMethodName               = "/app_service.AppService/GetAppKeyByKey"
	AppService_GetExplorationAppList_FullMethodName        = "/app_service.AppService/GetExplorationAppList"
	AppService_ChangeExplorationAppFavorite_FullMethodName = "/app_service.AppService/ChangeExplorationAppFavorite"
	AppService_RecordAppHistory_FullMethodName             = "/app_service.AppService/RecordAppHistory"
	AppService_PublishApp_FullMethodName                   = "/app_service.AppService/PublishApp"
	AppService_UnPublishApp_FullMethodName                 = "/app_service.AppService/UnPublishApp"
	AppService_GetAppList_FullMethodName                   = "/app_service.AppService/GetAppList"
	AppService_GetAppListByIds_FullMethodName              = "/app_service.AppService/GetAppListByIds"
	AppService_DeleteApp_FullMethodName                    = "/app_service.AppService/DeleteApp"
	AppService_GetAppInfo_FullMethodName                   = "/app_service.AppService/GetAppInfo"
	AppService_ConvertAppType_FullMethodName               = "/app_service.AppService/ConvertAppType"
	AppService_AppUrlCreate_FullMethodName                 = "/app_service.AppService/AppUrlCreate"
	AppService_AppUrlDelete_FullMethodName                 = "/app_service.AppService/AppUrlDelete"
	AppService_AppUrlUpdate_FullMethodName                 = "/app_service.AppService/AppUrlUpdate"
	AppService_GetAppUrlList_FullMethodName                = "/app_service.AppService/GetAppUrlList"
	AppService_GetAppUrlInfoBySuffix_FullMethodName        = "/app_service.AppService/GetAppUrlInfoBySuffix"
	AppService_AppUrlStatusSwitch_FullMethodName           = "/app_service.AppService/AppUrlStatusSwitch"
	AppService_GetConversationByID_FullMethodName          = "/app_service.AppService/GetConversationByID"
	AppService_CreateConversation_FullMethodName           = "/app_service.AppService/CreateConversation"
	AppService_GetChatflowApplication_FullMethodName       = "/app_service.AppService/GetChatflowApplication"
	AppService_GetChatflowByApplicationID_FullMethodName   = "/app_service.AppService/GetChatflowByApplicationID"
	AppService_CreateChatflowApplication_FullMethodName    = "/app_service.AppService/CreateChatflowApplication"
	AppService_GetModelStatistic_FullMethodName            = "/app_service.AppService/GetModelStatistic"
	AppService_RecordModelStatistic_FullMethodName         = "/app_service.AppService/RecordModelStatistic"
	AppService_GetModelStatisticList_FullMethodName        = "/app_service.AppService/GetModelStatisticList"
)

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppServiceClient interface {
	// --- apiKey ---
	CreateApiKey(ctx context.Context, in *CreateApiKeyReq, opts ...grpc.CallOption) (*ApiKeyInfo, error)
	DeleteApiKey(ctx context.Context, in *DeleteApiKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListApiKeys(ctx context.Context, in *ListApiKeysReq, opts ...grpc.CallOption) (*ApiKeyInfoList, error)
	UpdateApiKey(ctx context.Context, in *UpdateApiKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateApiKeyStatus(ctx context.Context, in *UpdateApiKeyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetApiKeyByKey(ctx context.Context, in *GetApiKeyByKeyReq, opts ...grpc.CallOption) (*ApiKeyInfo, error)
	// --- appKey ---
	GenAppKey(ctx context.Context, in *GenAppKeyReq, opts ...grpc.CallOption) (*AppKeyInfo, error)
	GetAppKeyList(ctx context.Context, in *GetAppKeyListReq, opts ...grpc.CallOption) (*AppKeyInfoList, error)
	DelAppKey(ctx context.Context, in *DelAppKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAppKeyByKey(ctx context.Context, in *GetAppKeyByKeyReq, opts ...grpc.CallOption) (*AppKeyInfo, error)
	// --- exploration ---
	GetExplorationAppList(ctx context.Context, in *GetExplorationAppListReq, opts ...grpc.CallOption) (*ExplorationAppList, error)
	ChangeExplorationAppFavorite(ctx context.Context, in *ChangeExplorationAppFavoriteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RecordAppHistory(ctx context.Context, in *RecordAppHistoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- app ---
	PublishApp(ctx context.Context, in *PublishAppReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnPublishApp(ctx context.Context, in *UnPublishAppReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAppList(ctx context.Context, in *GetAppListReq, opts ...grpc.CallOption) (*AppList, error)
	GetAppListByIds(ctx context.Context, in *GetAppListByIdsReq, opts ...grpc.CallOption) (*AppList, error)
	DeleteApp(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAppInfo(ctx context.Context, in *GetAppInfoReq, opts ...grpc.CallOption) (*AppInfo, error)
	ConvertAppType(ctx context.Context, in *ConvertAppTypeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- url ---
	AppUrlCreate(ctx context.Context, in *AppUrlCreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppUrlDelete(ctx context.Context, in *AppUrlDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppUrlUpdate(ctx context.Context, in *AppUrlUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAppUrlList(ctx context.Context, in *GetAppUrlListReq, opts ...grpc.CallOption) (*GetAppUrlListResp, error)
	GetAppUrlInfoBySuffix(ctx context.Context, in *GetAppUrlInfoBySuffixReq, opts ...grpc.CallOption) (*AppUrlInfo, error)
	AppUrlStatusSwitch(ctx context.Context, in *AppUrlStatusSwitchReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- conversation ---
	GetConversationByID(ctx context.Context, in *GetConversationByIDReq, opts ...grpc.CallOption) (*ConversationInfo, error)
	CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- chatflowApplication ---
	GetChatflowApplication(ctx context.Context, in *GetChatflowApplicationReq, opts ...grpc.CallOption) (*ChatflowApplicationInfo, error)
	GetChatflowByApplicationID(ctx context.Context, in *GetChatflowByApplicationIDReq, opts ...grpc.CallOption) (*ChatflowApplicationInfo, error)
	CreateChatflowApplication(ctx context.Context, in *CreateChatflowApplicationReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- statistic ---
	GetModelStatistic(ctx context.Context, in *GetModelStatisticReq, opts ...grpc.CallOption) (*ModelStatistic, error)
	RecordModelStatistic(ctx context.Context, in *RecordModelStatisticReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetModelStatisticList(ctx context.Context, in *GetModelStatisticListReq, opts ...grpc.CallOption) (*GetModelStatisticListResp, error)
}

type appServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppServiceClient(cc grpc.ClientConnInterface) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) CreateApiKey(ctx context.Context, in *CreateApiKeyReq, opts ...grpc.CallOption) (*ApiKeyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyInfo)
	err := c.cc.Invoke(ctx, AppService_CreateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DeleteApiKey(ctx context.Context, in *DeleteApiKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_DeleteApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ListApiKeys(ctx context.Context, in *ListApiKeysReq, opts ...grpc.CallOption) (*ApiKeyInfoList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyInfoList)
	err := c.cc.Invoke(ctx, AppService_ListApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) UpdateApiKey(ctx context.Context, in *UpdateApiKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_UpdateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) UpdateApiKeyStatus(ctx context.Context, in *UpdateApiKeyStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_UpdateApiKeyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetApiKeyByKey(ctx context.Context, in *GetApiKeyByKeyReq, opts ...grpc.CallOption) (*ApiKeyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyInfo)
	err := c.cc.Invoke(ctx, AppService_GetApiKeyByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GenAppKey(ctx context.Context, in *GenAppKeyReq, opts ...grpc.CallOption) (*AppKeyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppKeyInfo)
	err := c.cc.Invoke(ctx, AppService_GenAppKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppKeyList(ctx context.Context, in *GetAppKeyListReq, opts ...grpc.CallOption) (*AppKeyInfoList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppKeyInfoList)
	err := c.cc.Invoke(ctx, AppService_GetAppKeyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DelAppKey(ctx context.Context, in *DelAppKeyReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_DelAppKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppKeyByKey(ctx context.Context, in *GetAppKeyByKeyReq, opts ...grpc.CallOption) (*AppKeyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppKeyInfo)
	err := c.cc.Invoke(ctx, AppService_GetAppKeyByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetExplorationAppList(ctx context.Context, in *GetExplorationAppListReq, opts ...grpc.CallOption) (*ExplorationAppList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplorationAppList)
	err := c.cc.Invoke(ctx, AppService_GetExplorationAppList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ChangeExplorationAppFavorite(ctx context.Context, in *ChangeExplorationAppFavoriteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_ChangeExplorationAppFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) RecordAppHistory(ctx context.Context, in *RecordAppHistoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_RecordAppHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) PublishApp(ctx context.Context, in *PublishAppReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_PublishApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) UnPublishApp(ctx context.Context, in *UnPublishAppReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_UnPublishApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppList(ctx context.Context, in *GetAppListReq, opts ...grpc.CallOption) (*AppList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppList)
	err := c.cc.Invoke(ctx, AppService_GetAppList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppListByIds(ctx context.Context, in *GetAppListByIdsReq, opts ...grpc.CallOption) (*AppList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppList)
	err := c.cc.Invoke(ctx, AppService_GetAppListByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DeleteApp(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_DeleteApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppInfo(ctx context.Context, in *GetAppInfoReq, opts ...grpc.CallOption) (*AppInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppInfo)
	err := c.cc.Invoke(ctx, AppService_GetAppInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ConvertAppType(ctx context.Context, in *ConvertAppTypeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_ConvertAppType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AppUrlCreate(ctx context.Context, in *AppUrlCreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_AppUrlCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AppUrlDelete(ctx context.Context, in *AppUrlDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_AppUrlDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AppUrlUpdate(ctx context.Context, in *AppUrlUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_AppUrlUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppUrlList(ctx context.Context, in *GetAppUrlListReq, opts ...grpc.CallOption) (*GetAppUrlListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppUrlListResp)
	err := c.cc.Invoke(ctx, AppService_GetAppUrlList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppUrlInfoBySuffix(ctx context.Context, in *GetAppUrlInfoBySuffixReq, opts ...grpc.CallOption) (*AppUrlInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppUrlInfo)
	err := c.cc.Invoke(ctx, AppService_GetAppUrlInfoBySuffix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AppUrlStatusSwitch(ctx context.Context, in *AppUrlStatusSwitchReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_AppUrlStatusSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetConversationByID(ctx context.Context, in *GetConversationByIDReq, opts ...grpc.CallOption) (*ConversationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationInfo)
	err := c.cc.Invoke(ctx, AppService_GetConversationByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_CreateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetChatflowApplication(ctx context.Context, in *GetChatflowApplicationReq, opts ...grpc.CallOption) (*ChatflowApplicationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatflowApplicationInfo)
	err := c.cc.Invoke(ctx, AppService_GetChatflowApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetChatflowByApplicationID(ctx context.Context, in *GetChatflowByApplicationIDReq, opts ...grpc.CallOption) (*ChatflowApplicationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatflowApplicationInfo)
	err := c.cc.Invoke(ctx, AppService_GetChatflowByApplicationID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) CreateChatflowApplication(ctx context.Context, in *CreateChatflowApplicationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_CreateChatflowApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetModelStatistic(ctx context.Context, in *GetModelStatisticReq, opts ...grpc.CallOption) (*ModelStatistic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelStatistic)
	err := c.cc.Invoke(ctx, AppService_GetModelStatistic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) RecordModelStatistic(ctx context.Context, in *RecordModelStatisticReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppService_RecordModelStatistic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetModelStatisticList(ctx context.Context, in *GetModelStatisticListReq, opts ...grpc.CallOption) (*GetModelStatisticListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelStatisticListResp)
	err := c.cc.Invoke(ctx, AppService_GetModelStatisticList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
// All implementations must embed UnimplementedAppServiceServer
// for forward compatibility.
type AppServiceServer interface {
	// --- apiKey ---
	CreateApiKey(context.Context, *CreateApiKeyReq) (*ApiKeyInfo, error)
	DeleteApiKey(context.Context, *DeleteApiKeyReq) (*emptypb.Empty, error)
	ListApiKeys(context.Context, *ListApiKeysReq) (*ApiKeyInfoList, error)
	UpdateApiKey(context.Context, *UpdateApiKeyReq) (*emptypb.Empty, error)
	UpdateApiKeyStatus(context.Context, *UpdateApiKeyStatusReq) (*emptypb.Empty, error)
	GetApiKeyByKey(context.Context, *GetApiKeyByKeyReq) (*ApiKeyInfo, error)
	// --- appKey ---
	GenAppKey(context.Context, *GenAppKeyReq) (*AppKeyInfo, error)
	GetAppKeyList(context.Context, *GetAppKeyListReq) (*AppKeyInfoList, error)
	DelAppKey(context.Context, *DelAppKeyReq) (*emptypb.Empty, error)
	GetAppKeyByKey(context.Context, *GetAppKeyByKeyReq) (*AppKeyInfo, error)
	// --- exploration ---
	GetExplorationAppList(context.Context, *GetExplorationAppListReq) (*ExplorationAppList, error)
	ChangeExplorationAppFavorite(context.Context, *ChangeExplorationAppFavoriteReq) (*emptypb.Empty, error)
	RecordAppHistory(context.Context, *RecordAppHistoryReq) (*emptypb.Empty, error)
	// --- app ---
	PublishApp(context.Context, *PublishAppReq) (*emptypb.Empty, error)
	UnPublishApp(context.Context, *UnPublishAppReq) (*emptypb.Empty, error)
	GetAppList(context.Context, *GetAppListReq) (*AppList, error)
	GetAppListByIds(context.Context, *GetAppListByIdsReq) (*AppList, error)
	DeleteApp(context.Context, *DeleteAppReq) (*emptypb.Empty, error)
	GetAppInfo(context.Context, *GetAppInfoReq) (*AppInfo, error)
	ConvertAppType(context.Context, *ConvertAppTypeReq) (*emptypb.Empty, error)
	// --- url ---
	AppUrlCreate(context.Context, *AppUrlCreateReq) (*emptypb.Empty, error)
	AppUrlDelete(context.Context, *AppUrlDeleteReq) (*emptypb.Empty, error)
	AppUrlUpdate(context.Context, *AppUrlUpdateReq) (*emptypb.Empty, error)
	GetAppUrlList(context.Context, *GetAppUrlListReq) (*GetAppUrlListResp, error)
	GetAppUrlInfoBySuffix(context.Context, *GetAppUrlInfoBySuffixReq) (*AppUrlInfo, error)
	AppUrlStatusSwitch(context.Context, *AppUrlStatusSwitchReq) (*emptypb.Empty, error)
	// --- conversation ---
	GetConversationByID(context.Context, *GetConversationByIDReq) (*ConversationInfo, error)
	CreateConversation(context.Context, *CreateConversationReq) (*emptypb.Empty, error)
	// --- chatflowApplication ---
	GetChatflowApplication(context.Context, *GetChatflowApplicationReq) (*ChatflowApplicationInfo, error)
	GetChatflowByApplicationID(context.Context, *GetChatflowByApplicationIDReq) (*ChatflowApplicationInfo, error)
	CreateChatflowApplication(context.Context, *CreateChatflowApplicationReq) (*emptypb.Empty, error)
	// --- statistic ---
	GetModelStatistic(context.Context, *GetModelStatisticReq) (*ModelStatistic, error)
	RecordModelStatistic(context.Context, *RecordModelStatisticReq) (*emptypb.Empty, error)
	GetModelStatisticList(context.Context, *GetModelStatisticListReq) (*GetModelStatisticListResp, error)
	mustEmbedUnimplementedAppServiceServer()
}

// UnimplementedAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppServiceServer struct{}

func (UnimplementedAppServiceServer) CreateApiKey(context.Context, *CreateApiKeyReq) (*ApiKeyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApiKey not implemented")
}
func (UnimplementedAppServiceServer) DeleteApiKey(context.Context, *DeleteApiKeyReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApiKey not implemented")
}
func (UnimplementedAppServiceServer) ListApiKeys(context.Context, *ListApiKeysReq) (*ApiKeyInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApiKeys not implemented")
}
func (UnimplementedAppServiceServer) UpdateApiKey(context.Context, *UpdateApiKeyReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApiKey not implemented")
}
func (UnimplementedAppServiceServer) UpdateApiKeyStatus(context.Context, *UpdateApiKeyStatusReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApiKeyStatus not implemented")
}
func (UnimplementedAppServiceServer) GetApiKeyByKey(context.Context, *GetApiKeyByKeyReq) (*ApiKeyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiKeyByKey not implemented")
}
func (UnimplementedAppServiceServer) GenAppKey(context.Context, *GenAppKeyReq) (*AppKeyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenAppKey not implemented")
}
func (UnimplementedAppServiceServer) GetAppKeyList(context.Context, *GetAppKeyListReq) (*AppKeyInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppKeyList not implemented")
}
func (UnimplementedAppServiceServer) DelAppKey(context.Context, *DelAppKeyReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelAppKey not implemented")
}
func (UnimplementedAppServiceServer) GetAppKeyByKey(context.Context, *GetAppKeyByKeyReq) (*AppKeyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppKeyByKey not implemented")
}
func (UnimplementedAppServiceServer) GetExplorationAppList(context.Context, *GetExplorationAppListReq) (*ExplorationAppList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExplorationAppList not implemented")
}
func (UnimplementedAppServiceServer) ChangeExplorationAppFavorite(context.Context, *ChangeExplorationAppFavoriteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeExplorationAppFavorite not implemented")
}
func (UnimplementedAppServiceServer) RecordAppHistory(context.Context, *RecordAppHistoryReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordAppHistory not implemented")
}
func (UnimplementedAppServiceServer) PublishApp(context.Context, *PublishAppReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishApp not implemented")
}
func (UnimplementedAppServiceServer) UnPublishApp(context.Context, *UnPublishAppReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnPublishApp not implemented")
}
func (UnimplementedAppServiceServer) GetAppList(context.Context, *GetAppListReq) (*AppList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppList not implemented")
}
func (UnimplementedAppServiceServer) GetAppListByIds(context.Context, *GetAppListByIdsReq) (*AppList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppListByIds not implemented")
}
func (UnimplementedAppServiceServer) DeleteApp(context.Context, *DeleteAppReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApp not implemented")
}
func (UnimplementedAppServiceServer) GetAppInfo(context.Context, *GetAppInfoReq) (*AppInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppInfo not implemented")
}
func (UnimplementedAppServiceServer) ConvertAppType(context.Context, *ConvertAppTypeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertAppType not implemented")
}
func (UnimplementedAppServiceServer) AppUrlCreate(context.Context, *AppUrlCreateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppUrlCreate not implemented")
}
func (UnimplementedAppServiceServer) AppUrlDelete(context.Context, *AppUrlDeleteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppUrlDelete not implemented")
}
func (UnimplementedAppServiceServer) AppUrlUpdate(context.Context, *AppUrlUpdateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppUrlUpdate not implemented")
}
func (UnimplementedAppServiceServer) GetAppUrlList(context.Context, *GetAppUrlListReq) (*GetAppUrlListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppUrlList not implemented")
}
func (UnimplementedAppServiceServer) GetAppUrlInfoBySuffix(context.Context, *GetAppUrlInfoBySuffixReq) (*AppUrlInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppUrlInfoBySuffix not implemented")
}
func (UnimplementedAppServiceServer) AppUrlStatusSwitch(context.Context, *AppUrlStatusSwitchReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppUrlStatusSwitch not implemented")
}
func (UnimplementedAppServiceServer) GetConversationByID(context.Context, *GetConversationByIDReq) (*ConversationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationByID not implemented")
}
func (UnimplementedAppServiceServer) CreateConversation(context.Context, *CreateConversationReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversation not implemented")
}
func (UnimplementedAppServiceServer) GetChatflowApplication(context.Context, *GetChatflowApplicationReq) (*ChatflowApplicationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatflowApplication not implemented")
}
func (UnimplementedAppServiceServer) GetChatflowByApplicationID(context.Context, *GetChatflowByApplicationIDReq) (*ChatflowApplicationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatflowByApplicationID not implemented")
}
func (UnimplementedAppServiceServer) CreateChatflowApplication(context.Context, *CreateChatflowApplicationReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatflowApplication not implemented")
}
func (UnimplementedAppServiceServer) GetModelStatistic(context.Context, *GetModelStatisticReq) (*ModelStatistic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelStatistic not implemented")
}
func (UnimplementedAppServiceServer) RecordModelStatistic(context.Context, *RecordModelStatisticReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordModelStatistic not implemented")
}
func (UnimplementedAppServiceServer) GetModelStatisticList(context.Context, *GetModelStatisticListReq) (*GetModelStatisticListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelStatisticList not implemented")
}
func (UnimplementedAppServiceServer) mustEmbedUnimplementedAppServiceServer() {}
func (UnimplementedAppServiceServer) testEmbeddedByValue()                    {}

// UnsafeAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServiceServer will
// result in compilation errors.
type UnsafeAppServiceServer interface {
	mustEmbedUnimplementedAppServiceServer()
}

func RegisterAppServiceServer(s grpc.ServiceRegistrar, srv AppServiceServer) {
	// If the following call pancis, it indicates UnimplementedAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppService_ServiceDesc, srv)
}

func _AppService_CreateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_CreateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateApiKey(ctx, req.(*CreateApiKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DeleteApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DeleteApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_DeleteApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DeleteApiKey(ctx, req.(*DeleteApiKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ListApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApiKeysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ListApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ListApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ListApiKeys(ctx, req.(*ListApiKeysReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_UpdateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).UpdateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_UpdateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).UpdateApiKey(ctx, req.(*UpdateApiKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_UpdateApiKeyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiKeyStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).UpdateApiKeyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_UpdateApiKeyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).UpdateApiKeyStatus(ctx, req.(*UpdateApiKeyStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetApiKeyByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiKeyByKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetApiKeyByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetApiKeyByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetApiKeyByKey(ctx, req.(*GetApiKeyByKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GenAppKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenAppKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GenAppKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GenAppKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GenAppKey(ctx, req.(*GenAppKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppKeyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetAppKeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppKeyList(ctx, req.(*GetAppKeyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DelAppKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelAppKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DelAppKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_DelAppKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DelAppKey(ctx, req.(*DelAppKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppKeyByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppKeyByKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppKeyByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetAppKeyByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppKeyByKey(ctx, req.(*GetAppKeyByKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetExplorationAppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExplorationAppListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetExplorationAppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetExplorationAppList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetExplorationAppList(ctx, req.(*GetExplorationAppListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ChangeExplorationAppFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeExplorationAppFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ChangeExplorationAppFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ChangeExplorationAppFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ChangeExplorationAppFavorite(ctx, req.(*ChangeExplorationAppFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_RecordAppHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAppHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).RecordAppHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_RecordAppHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).RecordAppHistory(ctx, req.(*RecordAppHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_PublishApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).PublishApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_PublishApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).PublishApp(ctx, req.(*PublishAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_UnPublishApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnPublishAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).UnPublishApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_UnPublishApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).UnPublishApp(ctx, req.(*UnPublishAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetAppList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppList(ctx, req.(*GetAppListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppListByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppListByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppListByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetAppListByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppListByIds(ctx, req.(*GetAppListByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DeleteApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DeleteApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_DeleteApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DeleteApp(ctx, req.(*DeleteAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetAppInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppInfo(ctx, req.(*GetAppInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ConvertAppType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertAppTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ConvertAppType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ConvertAppType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ConvertAppType(ctx, req.(*ConvertAppTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AppUrlCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppUrlCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AppUrlCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_AppUrlCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AppUrlCreate(ctx, req.(*AppUrlCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AppUrlDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppUrlDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AppUrlDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_AppUrlDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AppUrlDelete(ctx, req.(*AppUrlDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AppUrlUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppUrlUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AppUrlUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_AppUrlUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AppUrlUpdate(ctx, req.(*AppUrlUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppUrlList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppUrlListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppUrlList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetAppUrlList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppUrlList(ctx, req.(*GetAppUrlListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppUrlInfoBySuffix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppUrlInfoBySuffixReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppUrlInfoBySuffix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetAppUrlInfoBySuffix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppUrlInfoBySuffix(ctx, req.(*GetAppUrlInfoBySuffixReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AppUrlStatusSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppUrlStatusSwitchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AppUrlStatusSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_AppUrlStatusSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AppUrlStatusSwitch(ctx, req.(*AppUrlStatusSwitchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetConversationByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetConversationByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetConversationByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetConversationByID(ctx, req.(*GetConversationByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_CreateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateConversation(ctx, req.(*CreateConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetChatflowApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatflowApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetChatflowApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetChatflowApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetChatflowApplication(ctx, req.(*GetChatflowApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetChatflowByApplicationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatflowByApplicationIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetChatflowByApplicationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetChatflowByApplicationID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetChatflowByApplicationID(ctx, req.(*GetChatflowByApplicationIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_CreateChatflowApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatflowApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateChatflowApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_CreateChatflowApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateChatflowApplication(ctx, req.(*CreateChatflowApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetModelStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelStatisticReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetModelStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetModelStatistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetModelStatistic(ctx, req.(*GetModelStatisticReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_RecordModelStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordModelStatisticReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).RecordModelStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_RecordModelStatistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).RecordModelStatistic(ctx, req.(*RecordModelStatisticReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetModelStatisticList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelStatisticListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetModelStatisticList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetModelStatisticList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetModelStatisticList(ctx, req.(*GetModelStatisticListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AppService_ServiceDesc is the grpc.ServiceDesc for AppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app_service.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApiKey",
			Handler:    _AppService_CreateApiKey_Handler,
		},
		{
			MethodName: "DeleteApiKey",
			Handler:    _AppService_DeleteApiKey_Handler,
		},
		{
			MethodName: "ListApiKeys",
			Handler:    _AppService_ListApiKeys_Handler,
		},
		{
			MethodName: "UpdateApiKey",
			Handler:    _AppService_UpdateApiKey_Handler,
		},
		{
			MethodName: "UpdateApiKeyStatus",
			Handler:    _AppService_UpdateApiKeyStatus_Handler,
		},
		{
			MethodName: "GetApiKeyByKey",
			Handler:    _AppService_GetApiKeyByKey_Handler,
		},
		{
			MethodName: "GenAppKey",
			Handler:    _AppService_GenAppKey_Handler,
		},
		{
			MethodName: "GetAppKeyList",
			Handler:    _AppService_GetAppKeyList_Handler,
		},
		{
			MethodName: "DelAppKey",
			Handler:    _AppService_DelAppKey_Handler,
		},
		{
			MethodName: "GetAppKeyByKey",
			Handler:    _AppService_GetAppKeyByKey_Handler,
		},
		{
			MethodName: "GetExplorationAppList",
			Handler:    _AppService_GetExplorationAppList_Handler,
		},
		{
			MethodName: "ChangeExplorationAppFavorite",
			Handler:    _AppService_ChangeExplorationAppFavorite_Handler,
		},
		{
			MethodName: "RecordAppHistory",
			Handler:    _AppService_RecordAppHistory_Handler,
		},
		{
			MethodName: "PublishApp",
			Handler:    _AppService_PublishApp_Handler,
		},
		{
			MethodName: "UnPublishApp",
			Handler:    _AppService_UnPublishApp_Handler,
		},
		{
			MethodName: "GetAppList",
			Handler:    _AppService_GetAppList_Handler,
		},
		{
			MethodName: "GetAppListByIds",
			Handler:    _AppService_GetAppListByIds_Handler,
		},
		{
			MethodName: "DeleteApp",
			Handler:    _AppService_DeleteApp_Handler,
		},
		{
			MethodName: "GetAppInfo",
			Handler:    _AppService_GetAppInfo_Handler,
		},
		{
			MethodName: "ConvertAppType",
			Handler:    _AppService_ConvertAppType_Handler,
		},
		{
			MethodName: "AppUrlCreate",
			Handler:    _AppService_AppUrlCreate_Handler,
		},
		{
			MethodName: "AppUrlDelete",
			Handler:    _AppService_AppUrlDelete_Handler,
		},
		{
			MethodName: "AppUrlUpdate",
			Handler:    _AppService_AppUrlUpdate_Handler,
		},
		{
			MethodName: "GetAppUrlList",
			Handler:    _AppService_GetAppUrlList_Handler,
		},
		{
			MethodName: "GetAppUrlInfoBySuffix",
			Handler:    _AppService_GetAppUrlInfoBySuffix_Handler,
		},
		{
			MethodName: "AppUrlStatusSwitch",
			Handler:    _AppService_AppUrlStatusSwitch_Handler,
		},
		{
			MethodName: "GetConversationByID",
			Handler:    _AppService_GetConversationByID_Handler,
		},
		{
			MethodName: "CreateConversation",
			Handler:    _AppService_CreateConversation_Handler,
		},
		{
			MethodName: "GetChatflowApplication",
			Handler:    _AppService_GetChatflowApplication_Handler,
		},
		{
			MethodName: "GetChatflowByApplicationID",
			Handler:    _AppService_GetChatflowByApplicationID_Handler,
		},
		{
			MethodName: "CreateChatflowApplication",
			Handler:    _AppService_CreateChatflowApplication_Handler,
		},
		{
			MethodName: "GetModelStatistic",
			Handler:    _AppService_GetModelStatistic_Handler,
		},
		{
			MethodName: "RecordModelStatistic",
			Handler:    _AppService_RecordModelStatistic_Handler,
		},
		{
			MethodName: "GetModelStatisticList",
			Handler:    _AppService_GetModelStatisticList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/app-service/app-service.proto",
}
