// Package openurl Code generated by swaggo/swag. DO NOT EDIT
package openurl

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent/{suffix}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取智能体url信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openurl"
                ],
                "summary": "获取智能体url信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "临时唯一标识",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Url后缀",
                        "name": "suffix",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AppUrlConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/agent/{suffix}/conversation": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "创建智能体对话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openurl"
                ],
                "summary": "创建智能体对话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "临时唯一标识",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Url后缀",
                        "name": "suffix",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "智能体对话创建参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UrlConversationCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ConversationCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除智能体对话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openurl"
                ],
                "summary": "删除智能体对话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "临时唯一标识",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Url后缀",
                        "name": "suffix",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "智能体对话的id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ConversationIdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/agent/{suffix}/conversation/detail": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "智能体对话详情历史列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openurl"
                ],
                "summary": "智能体对话详情历史列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "临时唯一标识",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Url后缀",
                        "name": "suffix",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "智能体对话id",
                        "name": "conversationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ListResult"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/response.ConversationDetailInfo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/agent/{suffix}/conversation/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取智能体对话列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openurl"
                ],
                "summary": "获取智能体对话列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "临时唯一标识",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Url后缀",
                        "name": "suffix",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.ListResult"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/response.ConversationInfo"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/agent/{suffix}/recommend": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "智能体推荐问题",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openurl"
                ],
                "summary": "智能体推荐问题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "临时唯一标识",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Url后缀",
                        "name": "suffix",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "智能体推荐问题参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UrlQuestionRecommendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/agent/{suffix}/stream": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "智能体流式问答",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openurl"
                ],
                "summary": "智能体流式问答",
                "parameters": [
                    {
                        "type": "string",
                        "description": "临时唯一标识",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Url后缀",
                        "name": "suffix",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "智能体流式问答参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UrlConversionStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mp.AppModelParams": {
            "type": "object",
            "properties": {
                "providerDeepSeek": {
                    "$ref": "#/definitions/mp.AppModelParamsDeepSeek"
                },
                "providerHuoshan": {
                    "$ref": "#/definitions/mp.AppModelParamsHuoShan"
                },
                "providerInfini": {
                    "$ref": "#/definitions/mp.AppModelParamsInfini"
                },
                "providerOllama": {
                    "$ref": "#/definitions/mp.AppModelParamsOllama"
                },
                "providerOpenAICompatible": {
                    "description": "OpenAI-API-compatible模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp.AppModelParamsOpenAICompatible"
                        }
                    ]
                },
                "providerQianFan": {
                    "$ref": "#/definitions/mp.AppModelParamsQianFan"
                },
                "providerQwen": {
                    "$ref": "#/definitions/mp.AppModelParamsQwen"
                },
                "providerYuanjing": {
                    "description": "YuanJing模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp.AppModelParamsYuanjing"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsDeepSeek": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsHuoShan": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsInfini": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsOllama": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsOpenAICompatible": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsQianFan": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsQwen": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp.AppModelParamsYuanjing": {
            "type": "object",
            "properties": {
                "llm": {
                    "description": "大语言模型配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp_common.LLMParams"
                        }
                    ]
                }
            }
        },
        "mp_common.LLMParams": {
            "type": "object",
            "properties": {
                "frequencyPenalty": {
                    "description": "频率惩罚",
                    "type": "number"
                },
                "frequencyPenaltyEnable": {
                    "description": "频率惩罚(开关)",
                    "type": "boolean"
                },
                "maxTokens": {
                    "description": "最大标记",
                    "type": "integer"
                },
                "maxTokensEnable": {
                    "description": "最大标记(开关)",
                    "type": "boolean"
                },
                "presencePenalty": {
                    "description": "存在惩罚",
                    "type": "number"
                },
                "presencePenaltyEnable": {
                    "description": "存在惩罚(开关)",
                    "type": "boolean"
                },
                "temperature": {
                    "description": "温度",
                    "type": "number"
                },
                "temperatureEnable": {
                    "description": "温度(开关)",
                    "type": "boolean"
                },
                "topP": {
                    "description": "Top P",
                    "type": "number"
                },
                "topPEnable": {
                    "description": "Top P(开关)",
                    "type": "boolean"
                }
            }
        },
        "request.AppKnowledgeBase": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "category": {
                    "description": "知识库类别 0-知识库，1-问答库，2-多模态知识库",
                    "type": "integer"
                },
                "external": {
                    "description": "外部数据库标识",
                    "type": "integer"
                },
                "graphSwitch": {
                    "description": "知识图谱开关",
                    "type": "integer"
                },
                "id": {
                    "description": "知识库id",
                    "type": "string"
                },
                "metaDataFilterParams": {
                    "$ref": "#/definitions/request.MetaDataFilterParams"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.AppKnowledgebaseConfig": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "知识库参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.AppKnowledgebaseParams"
                        }
                    ]
                },
                "knowledgebases": {
                    "description": "知识库id、名字",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.AppKnowledgeBase"
                    }
                }
            }
        },
        "request.AppKnowledgebaseParams": {
            "type": "object",
            "properties": {
                "keywordPriority": {
                    "description": "关键词权重",
                    "type": "number"
                },
                "matchType": {
                    "description": "matchType：vector（向量检索）、text（文本检索）、mix（混合检索：向量+文本）",
                    "type": "string"
                },
                "maxHistory": {
                    "description": "最长上下文",
                    "type": "integer"
                },
                "priorityMatch": {
                    "description": "权重匹配，只有在混合检索模式下，选择权重设置后，这个才设置为1",
                    "type": "integer"
                },
                "semanticsPriority": {
                    "description": "语义权重",
                    "type": "number"
                },
                "termWeight": {
                    "description": "关键词系数，默认为1",
                    "type": "number"
                },
                "termWeightEnable": {
                    "description": "关键词系数开关",
                    "type": "boolean"
                },
                "threshold": {
                    "description": "过滤阈值",
                    "type": "number"
                },
                "topK": {
                    "description": "知识条数",
                    "type": "integer"
                },
                "useGraph": {
                    "description": "知识图谱开关",
                    "type": "boolean"
                }
            }
        },
        "request.AppModelConfig": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "模型配置"
                },
                "displayName": {
                    "description": "模型展示名称(请求非必填)",
                    "type": "string"
                },
                "examples": {
                    "description": "仅用于swagger展示；模型对应供应商中的对应llm、embedding或rerank结构是config实际的参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mp.AppModelParams"
                        }
                    ]
                },
                "model": {
                    "description": "模型名称",
                    "type": "string"
                },
                "modelId": {
                    "description": "模型ID",
                    "type": "string"
                },
                "modelType": {
                    "description": "模型类型(llm/embedding/rerank)",
                    "type": "string"
                },
                "provider": {
                    "description": "模型供应商",
                    "type": "string"
                }
            }
        },
        "request.AppSafetyConfig": {
            "type": "object",
            "properties": {
                "enable": {
                    "description": "安全护栏(开关)",
                    "type": "boolean"
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.SensitiveTable"
                    }
                }
            }
        },
        "request.AssistantToolConfig": {
            "type": "object",
            "properties": {
                "rerankId": {
                    "type": "string"
                }
            }
        },
        "request.Avatar": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "前端透传给后端用于保存avatar，例如：custom-upload/avatar/abc/def.png",
                    "type": "string"
                },
                "path": {
                    "description": "前端请求地址，例如：/v1/static/avatar/abc/def.png (请求非必填)",
                    "type": "string"
                }
            }
        },
        "request.ConversationIdRequest": {
            "type": "object",
            "required": [
                "conversationId"
            ],
            "properties": {
                "conversationId": {
                    "type": "string"
                }
            }
        },
        "request.MemoryConfig": {
            "type": "object",
            "properties": {
                "maxHistoryLength": {
                    "type": "integer"
                }
            }
        },
        "request.MetaDataFilterParams": {
            "type": "object",
            "properties": {
                "filterEnable": {
                    "description": "元数据过滤开关",
                    "type": "boolean"
                },
                "filterLogicType": {
                    "description": "元数据逻辑条件：and/or",
                    "type": "string"
                },
                "metaFilterParams": {
                    "description": "元数据过滤参数列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.MetaFilterParams"
                    }
                }
            }
        },
        "request.MetaFilterParams": {
            "type": "object",
            "properties": {
                "condition": {
                    "description": "条件",
                    "type": "string"
                },
                "key": {
                    "description": "Key",
                    "type": "string"
                },
                "type": {
                    "description": "类型（Time, String, Number）",
                    "type": "string"
                },
                "value": {
                    "description": "value",
                    "type": "string"
                }
            }
        },
        "request.SensitiveTable": {
            "type": "object",
            "required": [
                "tableId"
            ],
            "properties": {
                "tableId": {
                    "description": "敏感词表id",
                    "type": "string"
                },
                "tableName": {
                    "description": "敏感词表名称(请求非必填)",
                    "type": "string"
                }
            }
        },
        "request.UrlConversationCreateRequest": {
            "type": "object",
            "required": [
                "prompt"
            ],
            "properties": {
                "prompt": {
                    "type": "string"
                }
            }
        },
        "request.UrlConversionStreamRequest": {
            "type": "object",
            "required": [
                "prompt"
            ],
            "properties": {
                "conversationId": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                }
            }
        },
        "request.UrlQuestionRecommendRequest": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "conversationId": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "response.AppUrlConfig": {
            "type": "object",
            "properties": {
                "appUrlInfo": {
                    "description": "应用Url信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.AppUrlInfo"
                        }
                    ]
                },
                "assistant": {
                    "description": "基本信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Assistant"
                        }
                    ]
                }
            }
        },
        "response.AppUrlInfo": {
            "type": "object",
            "properties": {
                "appId": {
                    "description": "应用ID",
                    "type": "string"
                },
                "appType": {
                    "description": "应用类型",
                    "type": "string"
                },
                "copyright": {
                    "description": "知识产权",
                    "type": "string"
                },
                "copyrightEnable": {
                    "description": "知识产权开关",
                    "type": "boolean"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "应用描述",
                    "type": "string"
                },
                "disclaimer": {
                    "description": "免责声明",
                    "type": "string"
                },
                "disclaimerEnable": {
                    "description": "免责声明开关",
                    "type": "boolean"
                },
                "expiredAt": {
                    "description": "过期时间",
                    "type": "string"
                },
                "name": {
                    "description": "Url名称",
                    "type": "string"
                },
                "orgId": {
                    "description": "组织ID",
                    "type": "string"
                },
                "privacyPolicy": {
                    "description": "隐私政策",
                    "type": "string"
                },
                "privacyPolicyEnable": {
                    "description": "隐私政策开关",
                    "type": "boolean"
                },
                "status": {
                    "description": "应用Url开关",
                    "type": "boolean"
                },
                "suffix": {
                    "description": "生成Url后缀",
                    "type": "string"
                },
                "urlId": {
                    "description": "UrlID",
                    "type": "string"
                },
                "userId": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        },
        "response.Assistant": {
            "type": "object",
            "required": [
                "assistantId",
                "name"
            ],
            "properties": {
                "assistantId": {
                    "type": "string"
                },
                "avatar": {
                    "description": "图标",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.Avatar"
                        }
                    ]
                },
                "category": {
                    "description": "智能体分类 1.单智能体 2.多智能体",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "description": "描述",
                    "type": "string"
                },
                "instructions": {
                    "description": "系统提示词",
                    "type": "string"
                },
                "knowledgeBaseConfig": {
                    "description": "知识库",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.AppKnowledgebaseConfig"
                        }
                    ]
                },
                "mcpInfos": {
                    "description": "MCP信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AssistantMCPInfo"
                    }
                },
                "memoryConfig": {
                    "description": "记忆配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.MemoryConfig"
                        }
                    ]
                },
                "modelConfig": {
                    "description": "模型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.AppModelConfig"
                        }
                    ]
                },
                "multiAgentInfos": {
                    "description": "多智能体配置",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AssistantAgentInfo"
                    }
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "newAgent": {
                    "description": "是否是新版本智能体",
                    "type": "boolean"
                },
                "prologue": {
                    "description": "开场白",
                    "type": "string"
                },
                "publishType": {
                    "description": "发布类型",
                    "type": "string"
                },
                "recommendConfig": {
                    "description": "追问配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.RecommendConfig"
                        }
                    ]
                },
                "recommendQuestion": {
                    "description": "推荐问题",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rerankConfig": {
                    "description": "Rerank模型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.AppModelConfig"
                        }
                    ]
                },
                "safetyConfig": {
                    "description": "敏感词表配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.AppSafetyConfig"
                        }
                    ]
                },
                "scope": {
                    "description": "作用域",
                    "type": "integer"
                },
                "toolInfos": {
                    "description": "自定义工具、内置工具",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AssistantToolInfo"
                    }
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "visionConfig": {
                    "description": "视觉配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.VisionConfig"
                        }
                    ]
                },
                "workFlowInfos": {
                    "description": "工作流信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AssistantWorkFlowInfo"
                    }
                }
            }
        },
        "response.AssistantAgentInfo": {
            "type": "object",
            "properties": {
                "agentId": {
                    "type": "string"
                },
                "avatar": {
                    "$ref": "#/definitions/request.Avatar"
                },
                "desc": {
                    "type": "string"
                },
                "enable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.AssistantMCPInfo": {
            "type": "object",
            "required": [
                "mcpType"
            ],
            "properties": {
                "actionName": {
                    "type": "string"
                },
                "avatar": {
                    "$ref": "#/definitions/request.Avatar"
                },
                "enable": {
                    "type": "boolean"
                },
                "mcpId": {
                    "type": "string"
                },
                "mcpName": {
                    "type": "string"
                },
                "mcpType": {
                    "type": "string",
                    "enum": [
                        "mcp",
                        "mcpserver"
                    ]
                },
                "uniqueId": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "response.AssistantRequestFile": {
            "type": "object",
            "properties": {
                "fileUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "response.AssistantToolInfo": {
            "type": "object",
            "required": [
                "toolType"
            ],
            "properties": {
                "actionName": {
                    "type": "string"
                },
                "avatar": {
                    "$ref": "#/definitions/request.Avatar"
                },
                "enable": {
                    "type": "boolean"
                },
                "toolConfig": {
                    "$ref": "#/definitions/request.AssistantToolConfig"
                },
                "toolId": {
                    "type": "string"
                },
                "toolName": {
                    "type": "string"
                },
                "toolType": {
                    "type": "string",
                    "enum": [
                        "builtin",
                        "custom"
                    ]
                },
                "uniqueId": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "response.AssistantWorkFlowInfo": {
            "type": "object",
            "properties": {
                "apiName": {
                    "type": "string"
                },
                "avatar": {
                    "$ref": "#/definitions/request.Avatar"
                },
                "enable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "uniqueId": {
                    "type": "string"
                },
                "workFlowDesc": {
                    "type": "string"
                },
                "workFlowId": {
                    "type": "string"
                }
            }
        },
        "response.ConversationCreateResp": {
            "type": "object",
            "properties": {
                "conversationId": {
                    "type": "string"
                }
            }
        },
        "response.ConversationDetailInfo": {
            "type": "object",
            "properties": {
                "assistantId": {
                    "type": "string"
                },
                "conversationId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "integer"
                },
                "createdBy": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                },
                "qa_type": {
                    "type": "integer"
                },
                "requestFiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AssistantRequestFile"
                    }
                },
                "response": {
                    "type": "string"
                },
                "responseList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ConversationResponse"
                    }
                },
                "searchList": {},
                "subConversationList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SubConversation"
                    }
                },
                "sysPrompt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "integer"
                }
            }
        },
        "response.ConversationInfo": {
            "type": "object",
            "properties": {
                "assistantId": {
                    "type": "string"
                },
                "conversationId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.ConversationResponse": {
            "type": "object",
            "properties": {
                "order": {
                    "type": "integer"
                },
                "response": {
                    "type": "string"
                }
            }
        },
        "response.ListResult": {
            "type": "object",
            "properties": {
                "list": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.RecommendConfig": {
            "type": "object",
            "properties": {
                "maxHistory": {
                    "description": "最大历史会话轮次",
                    "type": "integer"
                },
                "modelConfig": {
                    "description": "模型信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request.AppModelConfig"
                        }
                    ]
                },
                "prompt": {
                    "description": "提示词",
                    "type": "string"
                },
                "promptEnable": {
                    "description": "提示词开关",
                    "type": "boolean"
                },
                "recommendEnable": {
                    "description": "追问配置开关",
                    "type": "boolean"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SubConversation": {
            "type": "object",
            "properties": {
                "conversationType": {
                    "description": "subAgent：子智能体；agentTool：主智能体工具；subAgentTool：子智能体工具",
                    "type": "string"
                },
                "id": {
                    "description": "事件id",
                    "type": "string"
                },
                "name": {
                    "description": "事件名称",
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "parentId": {
                    "description": "事件挂载id",
                    "type": "string"
                },
                "profile": {
                    "description": "事件头像",
                    "type": "string"
                },
                "response": {
                    "type": "string"
                },
                "searchList": {},
                "status": {
                    "description": "1:成功，2：失败",
                    "type": "integer"
                },
                "timeCost": {
                    "description": "耗时",
                    "type": "string"
                }
            }
        },
        "response.VisionConfig": {
            "type": "object",
            "properties": {
                "maxPicNum": {
                    "description": "最大图片数量",
                    "type": "integer"
                },
                "picNum": {
                    "description": "视觉配置图片数量",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.0.1",
	Host:             "",
	BasePath:         "/openurl/v1",
	Schemes:          []string{},
	Title:            "AI Agent Productivity Platform - OpenUrl",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
